app/urls.py
from django.urls import path

from . import views

app_name = 'app'

urlpatterns = [
    path('', views.index, name='index'),
]

appnpo/urls.py
from django.urls import path

from . import views


app_name = 'npo'

urlpatterns = [
    path('', views.index, name='index'),
    path('workspace/list/', views.WorkSpaceListView.as_view(), name='workspace_list'),
    path('<str:workspace_name>/', views.WorkSpaceView.as_view(), name='workspace'),
    path('<str:workspace_name>/scene/', views.SceneListView.as_view(), name='scene_list'),
    path('<str:workspace_name>/site/', views.SiteListView.as_view(), name='site_list'),
    path('<str:workspace_name>/cell/', views.CellListView.as_view(), name='cell_list'),
    # # 双参数的如果第一个参数和上面的重合一定要防在最下，不然识别会出问题， url是从上到下进行匹配的
    path('<str:workspace_name>/<str:scene_name>/', views.SceneView.as_view(), name='scene'),
    path('<str:workspace_name>/<str:scene_name>/map', views.SceneMapView.as_view(), name='scene_map'),
]

project/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from django.views.static import serve

from project import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    # app
    path('', include('app.urls', namespace='app')),
    # npo
    path('npo/', include('appnpo.urls', namespace='npo')),
    # ipark
    path('ipark/', include('appipark.urls', namespace='ipark')),
    path('ipark1/', include('appipark1.urls', namespace='ipark1')),
    path('ipark2/', include('appipark2.urls', namespace='ipark2')),
    # 媒体文件
    re_path(r'media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
]

appnpo/views.py
import json
from copy import copy
from django.shortcuts import render
from django.db import models
from app.views import MyView
from app.utils import mymap, myfuncs
from django.db.models import Count
from .models import WorkSpace, WorkSpaceEditForm, WorkSpaceForm
from .models import Cell, CellForm
from .models import Site, SiteForm
from .models import Scene, SceneForm
from .models import get_type_display


def index(request):
    return render(request, 'appnpo/index.html')


class WorkSpaceListView(MyView):
    def get(self, request):
        workspaces = WorkSpace.objects.all()
        context = {
            'workspaces': workspaces,
        }
        return render(request, 'appnpo/workspace_list.html', context=context)

    def get_form(self, request):
        result = {
            'errmsg': [],
        }
        workspace_name = request.POST.get('workspace_name')
        if workspace_name:
            workspace = WorkSpace.objects.get(workspace_name=workspace_name)
            workspace_form = WorkSpaceEditForm(instance=workspace)
            result['form'] = workspace_form.as_form(),
        else:
            result['form'] = WorkSpaceForm().as_form()
        return result

    def new_object(self, request):
        result = {
            'errmsg': [],
        }
        form = WorkSpaceForm(request.POST)
        if form.is_valid():
            form.save()
        else:
            for key, value in form.errors.items():
                result['errmsg'].append('{}:{}'.format(key, value))
        return result

    def delete_object(self, request):
        result = {
            'errmsg': [],
        }
        workspace_name = request.POST.get('workspace_name')
        workspace = WorkSpace.objects.get(workspace_name=workspace_name)
        workspace.delete()
        return result

    def edit_object(self, request, **kwargs):
        result = {
            'errmsg': [],
        }
        # 在request.POST中, data数据是修改前的原数据
        # data = request.POST.get('data')
        # 修改前数据
        workspace_name = request.POST.get('old_workspace_name')
        workspace = WorkSpace.objects.get(workspace_name=workspace_name)
        # form是修改后实例对应的form
        form = WorkSpaceForm(instance=workspace, data=request.POST)
        # has_changed() 判断是否发生了修改
        if form.has_changed():
            if 'workspace_type' in form.changed_data:
                result['errmsg'].append('无法修改工作空间类型，可以创建一个新的工作空间')
            elif form.is_valid():
                form.save()
            else:
                for key, value in form.errors.items():
                    result['errmsg'].append('{}:{}'.format(key, value))
        else:
            result['errmsg'].append('未作修改')
        return result


class WorkSpaceView(MyView):

    def get(self, request, **kwargs):
        workspace = WorkSpace.objects.get(**kwargs)

        scenes = workspace.scene_set.all()
        sites = workspace.site_set.all()
        cells = workspace.cell_set.all()

        scenes_count = scenes.count()

        sites_count = sites.count()
        indoor_sites_count = sites.filter(site_type='室分').count()
        outdoor_sites_count = sites.filter(site_type='宏站').count()
        type_unknown_sites_count = sites_count - indoor_sites_count - outdoor_sites_count

        need_recheck = False
        if not workspace.time_lastcheck:
            need_recheck = True
        elif workspace.time_lastcheck.strftime('%Y-%m-%d %H:%M:%S') != workspace.time_lastmodify.strftime('%Y-%m-%d %H:%M:%S'):
            need_recheck = True

        context = {
            'workspace': workspace,
            'scenes_count': scenes_count,
            'sites_count': sites_count,
            'indoor_sites_count': indoor_sites_count,
            'outdoor_sites_count': outdoor_sites_count,
            'type_unknown_sites_count': type_unknown_sites_count,
            'cells_count': cells.count(),
            'need_recheck': need_recheck,
        }
        return render(request, 'appnpo/workspace.html', context=context)

    def get_data_for_charts(self, request, workspace_name):
        result = {
            'errmsg': [],
            'data': {
                'scene_chart': [],
                'site_chart': [],
                'cell_chart': [],
                'site_nearby_chart': [],
            },
        }
        workspace = WorkSpace.objects.get(workspace_name=workspace_name)
        # scenne_chart
        scenes = workspace.scene_set.all()
        type_grouped_scenes = scenes.values('scene_type').annotate(count=Count('scene_type'))
        for group in type_grouped_scenes:
            result['data']['scene_chart'].append({
                'name': group['scene_type'],
                'value': group['count'],
            })
        # site_chart
        sites = workspace.site_set.all()
        # 按照'site_type', 'is_auto_created' 进行分组计数
        type_grouped_sites = sites.values('site_type', 'is_auto_created')
        type_grouped_sites = type_grouped_sites.annotate(Count('site_type'), count=Count('is_auto_created'))
        for group in type_grouped_sites:
            _name = get_type_display(group['site_type'])
            if group['is_auto_created']:
                _name += '_auto'
            result['data']['site_chart'].append({
                'name': _name,
                'value': group['count'],
            })
        # cell_chart
        cells = workspace.cell_set.all()
        type_grouped_cells = cells.values('cell_type').annotate(count=Count('cell_type'))
        for group in type_grouped_cells:
            result['data']['cell_chart'].append({
                'name': get_type_display(group['cell_type']),
                'value': group['count'],
            })
        # 结果
        outdoor_sites_nearby = [_scene.outdoorsitenearbyscene_set.count() for _scene in scenes]
        from collections import Counter
        _dict = Counter(sorted(outdoor_sites_nearby))
        result['data']['site_nearby_chart'] = [[], []]
        for key, value in _dict.items():
            result['data']['site_nearby_chart'][0].append(key)
            result['data']['site_nearby_chart'][1].append(value)
            # result['data']['site_nearby_chart'].append({
            #     'name': key,
            #     'value': value,
            # })
        # print(result['data']['site_nearby_chart'])
        # indoor_sites = workspace.indoorsiteinscene_set.all()
        return result

    def check(self, request, workspace_name):
        result = {
            'errmsg': [],
        }
        from . import outdoorsitenearbyscene
        from . import indoorsiteinscene
        _workspace = WorkSpace.objects.get(workspace_name=workspace_name)
        _workspace.outdoorsitenearbyscene_set.all().delete()
        _workspace.indoorsiteinscene_set.all().delete()
        scenes = _workspace.scene_set.all()
        if not scenes:
            result['errmsg'].append('请先创建场景数据！')
        sites = _workspace.site_set.all()
        if not sites:
            result['errmsg'].append('请先创建站址数据!')
        if not result['errmsg']:
            outdoor_sites = sites.filter(site_type='outdoor')
            if outdoor_sites:
                _result_sites = outdoorsitenearbyscene.get_sites_nearby_scenes(
                    scenes=scenes,
                    queryset_sites=outdoor_sites
                )
                outdoorsitenearbyscene.OutdoorSiteNearbyScene.objects.bulk_create(_result_sites)
                sites_nearby_scene = outdoorsitenearbyscene.OutdoorSiteNearbyScene.objects.all()
                _result_cells = outdoorsitenearbyscene.get_cells_cover_scenes(
                    scenes=scenes,
                    queryset_sites_nearby_scene=sites_nearby_scene,
                )
                outdoorsitenearbyscene.OutdoorCellCoverScene.objects.bulk_create(_result_cells)
            indoor_sites = sites.filter(site_type='indoor')
            if indoor_sites:
                indoor_sites_in_scenes = indoorsiteinscene.get_indoor_sites_in_scenes(
                    scenes=scenes,
                    queryset_sites=indoor_sites
                )
                indoorsiteinscene.IndoorSiteInScene.objects.bulk_create(indoor_sites_in_scenes)
            from datetime import datetime
            _workspace.time_lastcheck = datetime.now()
            _workspace.save()
        return result

    def export(self, request, workspace_name):
        result = {
            'errmsg': [],
            'data': [],
        }
        _workspace = WorkSpace.objects.get(workspace_name=workspace_name)
        scenes = _workspace.scene_set.all()
        for _scene in scenes:
            indoor_sites = _scene.indoorsiteinscene_set.all()
            for obj in indoor_sites:
                cells = obj.site.cell_set.all()
                for _cell in cells:
                    result['data'].append({
                        '场景编号': _scene.scene_id,
                        '场景名称': _scene.scene_name,
                        '场景类型': _scene.scene_type,
                        '小区类型': '室分',
                        '小区号': _cell.cell_id,
                        '小区名': _cell.cell_name,
                    })
            outdoor_sites = _scene.outdoorsitenearbyscene_set.all()
            for obj in outdoor_sites:
                if obj.in_scene:
                    cells = obj.site.cell_set.all()
                    for _cell in cells:
                        result['data'].append({
                            '场景编号': _scene.scene_id,
                            '场景名称': _scene.scene_name,
                            '场景类型': _scene.scene_type,
                            '小区类型': '宏站',
                            '小区号': _cell.cell_id,
                            '小区名': _cell.cell_name,
                        })
                elif obj.cover_order:
                    cells = obj.outdoorcellcoverscene_set.all()
                    for _cell in cells:
                        result['data'].append({
                            '场景编号': _scene.scene_id,

appnpo/templates/appnpo/base1.html
{% extends 'appnpo/base0.html' %}

{% block main0 %}
    <aside class="bg-light" style="width: 200px; position: absolute">
        <a name="left_open" href="javascript: void(0);" class="nav-link text-nowrap p-0 d-flex justify-content-end">
        <span class="fa fa-angle-left fa-fw fa-2x" data-toggle="tooltip" data-placement="right"
              title="合起侧边栏"></span>
        </a>
        <ul class="navbar-nav flex-column pl-3">
            <li class="nav-item text-nowrap overflow-hidden">
                <a class="nav-link" href="{% url 'npo:workspace' workspace.workspace_name %}">
                    <span style="font-size: 1.3rem">
                        <i class="fa fa-fw fa-home ml-2 mr-3"></i>
                        主页
                    </span>
                </a>
            </li>
            <li class="nav-item text-nowrap overflow-hidden">
                <a class="nav-link" href="{% url 'npo:scene_list' workspace.workspace_name %}">
                    <span style="font-size: 1.3rem">
                        <i class="fa fa-fw fa-building ml-2 mr-3"></i>
                        场景列表
                    </span>
                </a>
            </li>
            <li class="nav-item text-nowrap overflow-hidden">
                <a class="nav-link" href="{% url 'npo:site_list' workspace.workspace_name %}">
                    <span style="font-size: 1.3rem">
                        <i class="fa fa-fw fa-broadcast-tower ml-2 mr-3"></i>
                        站址列表
                    </span>
                </a>
            </li>
            <li class="nav-item text-nowrap overflow-hidden">
                <a class="nav-link" href="{% url 'npo:cell_list' workspace.workspace_name %}">
                    <span style="font-size: 1.3rem">
                        <i class="fa fa-fw fa-rss ml-2 mr-3"></i>
                        小区列表
                    </span>
                </a>
            </li>
        </ul>
    </aside>
    <main style="position: absolute; left: 200px; right: 0; width: auto">
        {% block main1 %}
        {% endblock main1 %}
    </main>
{% endblock main0 %}

{% block script0 %}
    <script>
        $(document).ready(function () {
            $("a[name='left_open']").on('click', function (event) {
                if ($('aside').css('width') === '200px') {
                    // 当前在展开状态
                    // 关闭侧边栏
                    $('aside').animate({'width': '66px'}, 100);
                    // 同时移动内容
                    $('main').animate({'left': '66px',}, 100);
                    // 修改按键图标指向为向右
                    $(this).children("span").removeClass("fa-angle-left");
                    $(this).children("span").addClass("fa-angle-right");
                    // 修改tooltag 提示信息
                    $(this).children("span").attr('title', '展开侧边栏');
                } else {
                    // 当前在关闭状态
                    // 打开侧边栏
                    $('aside').animate({'width': '200px'}, 100);
                    // 同时移动内容
                    $('main').animate({'left': '200px',}, 100);
                    // 修改按键图标指向为向左
                    $(this).children("span").removeClass("fa-angle-right");
                    $(this).children("span").addClass("fa-angle-left");
                    // 修改tooltag 提示信息
                    $(this).children("span").attr('title', '合起侧边栏');
                }
            });
        });
    </script>
    {% block script1 %}
    {% endblock script1 %}
{% endblock script0 %}

appnpo/templates/appnpo/scene_list.html
{% extends 'appnpo/base1.html' %}

{% block main1 %}
    <div class="container-fluid">
        <div class="row">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item">
                        <a href="{% url 'npo:workspace_list' %}">
                            项目列表
                        </a>
                    </li>
                    <li class="breadcrumb-item">
                        <a href="{% url 'npo:workspace' workspace.workspace_name %}">
                            项目--{{ workspace.workspace_name }}
                        </a>
                    </li>
                    <li class="breadcrumb-item active" aria-current="page">
                        场景列表
                    </li>
                </ol>
            </nav>
        </div>
        <table id="table" class="table table-sm table-bordered table-striped">
            <thead class="thead-dark">
            <tr>
                <th data-checkbox="true"></th>
                <th data-field="scene_id">场景编号</th>
                <th data-field="scene_name">场景名称</th>
                <th data-field="scene_type">场景类型</th>
                <th data-field="center.lng">中心经度</th>
                <th data-field="center.lat">中心纬度</th>
                <th data-align="center" data-formatter="operate_formatter" data-events="window.row_toolbar_events">操作
                </th>
            </tr>
            </thead>
        </table>
        <div class="row">
            <div id="toolbar">
                {# 将 一个url 保存成一个参数reply_url 此参数只在当前block生效  #}
                {% url 'npo:workspace' workspace.workspace_name as reply_url %}
                {# 将上面的参数传送给模板 only 表示模板只接受此处的参数，不从其他地方接受参数 #}
                {% include 'myinclude/bootstrap_table/toolbar_buttons/reply.html' with reply_url=reply_url only %}
                {% include 'myinclude/bootstrap_table/toolbar_buttons/new_object.html' %}
                {% include 'myinclude/bootstrap_table/toolbar_buttons/delete_selected.html' %}
                {% include 'myinclude/bootstrap_table/toolbar_buttons/download_template.html' %}
                {% include 'myinclude/bootstrap_table/toolbar_buttons/upload.html' %}
                {% include 'myinclude/bootstrap_table/toolbar_buttons/clear.html' %}
            </div>
            <div class="d-none" id="row_toolbar">
                <div class="btn-group">
                    <button  class="btn btn-primary btn-sm" type="button" name="enter"
                            data-toggle="tooltip" data-placement="top" title="查看详情" >
                        <i class="fa fa-book-open"></i>
                    </button>
                    {% include 'myinclude/bootstrap_table/row_toolbar_buttons/edit_object.html' %}
                    {% include 'myinclude/bootstrap_table/row_toolbar_buttons/delete_object.html' %}
                </div>
            </div>
        </div>
    </div>
{% endblock main1 %}

{% block script1 %}
    <script>
        $(document).ready(function () {
            show_bootstrap_table();
            if (window.row_toolbar_events === undefined) {
                window.row_toolbar_events = [];
            }
            window.row_toolbar_events['click button[name="enter"]'] = function (e, value, row, index) {
                //console.log("{% url 'npo:scene' workspace.workspace_name '{0}' %}".format(row.scene_name));
                // window.location.href = "{% url 'npo:scene' workspace.workspace_name '{0}' %}".format(row.scene_name);
                // 这里的url可能需要根据情况进行修改
                console.log(row.scene_name);
                window.location.href = '/npo/{{ workspace.workspace_name }}/{0}'.format(row.scene_name);
            };
        });
    </script>
{% endblock script1 %}

{% block script_after %}
    {% include 'myinclude/bootstrap_table/bootstrap_table.html' %}
{% endblock script_after %}

appnpo/templates/appnpo/workspace.html
{% extends 'appnpo/base1.html' %}

{% block main1 %}
    <div class="container-fluid">
        <div class="row">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item">
                        <a href="{% url 'npo:workspace_list' %}">
                            项目列表
                        </a>
                    </li>
                    <li class="breadcrumb-item active" aria-current="page">
                        项目--{{ workspace.workspace_name }}
                    </li>
                </ol>
            </nav>
        </div>
        <div class="row">
            <div class="container-fluid">
                <div class="card-deck">
                    <div class="card">
                        <div class="card-body">
                            <h5 class="card-title">项目名称：{{ workspace.workspace_name }}</h5>
                            <h4 class="card-subtitle mb-2 text-muted">最后更新时间：{{ workspace.time_lastmodify }}</h4>
                            <h4 class="card-subtitle mb-2 text-muted">
                                是否需要重新计算：
                                {% if need_recheck %}
                                    是
                                {% else %}
                                    否
                                {% endif %}
                            </h4>
                            <div class="m-2">
                                <button type="button" class="btn btn-primary btn-sm" name="check">重新计算</button>
                            </div>
                            <div class="m-2">
                                <button type="button" class="btn btn-primary btn-sm" name="export">导出结果</button>
                            </div>
                        </div>
                    </div>
                    <div class="card">
                        <div class="card-body">
                            <h5 class="card-title">场景</h5>
                            <h3 class="card-subtitle mb-2 text-muted">{{ scenes_count }}</h3>
                            <div id="scene_chart" style="width: 300px;height:200px;"></div>
                            <a href="{% url 'npo:scene_list' workspace.workspace_name %}" class="card-link">详情</a>
                        </div>
                    </div>
                    <div class="card">
                        <div class="card-body">
                            <h5 class="card-title">站址</h5>
                            <h3 class="card-subtitle mb-2 text-muted">{{ sites_count }}</h3>
                            <div id="site_chart" style="width: 300px; height: 200px"></div>
                            <a href="{% url 'npo:site_list' workspace.workspace_name %}" class="card-link">详情</a>
                        </div>
                    </div>
                    <div class="card">
                        <div class="card-body">
                            <h5 class="card-title">小区</h5>
                            <h3 class="card-subtitle mb-2 text-muted">{{ cells_count }}</h3>
                            <div id="cell_chart" style="width: 300px;height:200px;"></div>
                            <a href="{% url 'npo:cell_list' workspace.workspace_name %}" class="card-link">详情</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row m-2"></div>
        <div class="row">
            <card class="card">
                <div class="card-body">
                    <h5 class="card-title">相邻站址情况</h5>
                   <div id="site_nearby_chart" style="width: 1200px;height:300px;"></div>
                </div>
            </card>
        </div>
    </div>
{% endblock main1 %}

{% block script1 %}
    <script>
        $(document).ready(function () {
            let data = new FormData();
            data.append('post_type', 'get_data_for_charts');
            myajax({
                url: '',
                data: data,
                success: function (respon) {
                    // scene_chart
                    echarts.init(document.getElementById('scene_chart')).setOption({
                        tooltip: {
                            trigger: 'item',
                            formatter: '{a} <br/>{b}: {c} ({d}%)'
                        },
                        grid: {
                            // grid 定义图标在父元素中的位置
                            top: 30,
                            bottom: 30,
                            left: 40,
                        },
                        xAxis: {
                            type: 'value',
                        },
                        yAxis: {
                            type: 'category',
                            inverse: true,
                        },
                        series: [
                            {
                                type: 'bar',
                                data: respon.data['scene_chart'],
                                // 是否启用防止标签重叠策略，默认开启，在标签拥挤重叠的情况下会挪动各个标签的位置，防止标签间的重叠。
                                avoidLabelOverlap: true,
                                // 标签设置
                                label: {
                                    // 标签显示格式  b 是数据名 c代表数据值
                                    formatter: '{b}:{c}',
                                    show: true,
                                    // 显示位置
                                    position: 'right',
                                },
                                itemStyle: {
                                    color: function (params) {
                                        let colorList = [
                                            "#c23531", "#2f4554", "#61a0a8", "#d48265", "#91c7ae", "#749f83", "#ca8622", "#bda29a",
                                            "#6e7074", "#546570", "#c4ccd3", "#4BABDE", "#FFDE76", "#E43C59", "#37A2DA"
                                        ];
                                        return colorList[params.dataIndex];
                                    }
                                }
                            }
                        ]
                    });
                    // site_chart
                    echarts.init(document.getElementById('site_chart')).setOption({
                        tooltip: {
                            trigger: 'item',
                            formatter: '{a} <br/>{b}: {c} ({d}%)'
                        },
                        grid: {
                            // grid 定义图标在父元素中的位置
                            top: 30,
                            bottom: 30,
                            left: 40,
                        },
                        xAxis: {
                            type: 'category',
                        },
                        yAxis: {
                            type: 'value',

                        },
                        series: [
                            {
                                // type 代表图标类型 pie 为饼图
                                type: 'bar',
                                data: respon.data['site_chart'],
                                // 是否启用防止标签重叠策略，默认开启，在标签拥挤重叠的情况下会挪动各个标签的位置，防止标签间的重叠。
                                avoidLabelOverlap: true,
                                // 标签设置
                                label: {
                                    // 标签显示格式  b 是数据名 c代表数据值
                                    formatter: '{b}:{c}',
                                    show: true,
                                    // 显示位置
                                    position: 'top',
                                    // 标签旋转
                                    rotate: 0,
                                },
                                itemStyle: {
                                    color: function (params) {
                                        let colorList = [
                                            "#c23531", "#2f4554", "#61a0a8", "#d48265", "#91c7ae", "#749f83", "#ca8622", "#bda29a",
                                            "#6e7074", "#546570", "#c4ccd3", "#4BABDE", "#FFDE76", "#E43C59", "#37A2DA"
                                        ];
                                        return colorList[params.dataIndex];
                                    }
                                }
                            },
                        ]
                    });
                    // cell_chart
                    echarts.init(document.getElementById('cell_chart')).setOption({
                        tooltip: {
                            trigger: 'item',
                            formatter: '{a} <br/>{b}: {c} ({d}%)'
                        },
                        series: [
                            {
                                // type 代表图标类型 pie 为饼图
                                type: 'pie',
                                // radius 饼图的半径 [内径,外径] 决定饼的大小， 内径大于0% 可以将饼设置为圆环
                                radius: ['30%', '100%'],
                                // 是否启用防止标签重叠策略，默认开启，在标签拥挤重叠的情况下会挪动各个标签的位置，防止标签间的重叠。
                                avoidLabelOverlap: true,
                                // 标签设置
                                label: {
                                    // 标签显示格式  b 是数据名 c代表数据值
                                    formatter: '{b}:{c}',
                                    show: true,
                                    // 显示位置
                                    position: 'inside',
                                },
                                data: respon.data['cell_chart'],
                            }
                        ]
                    });
                    // site_nearby_chart
                    echarts.init(document.getElementById('site_nearby_chart')).setOption({
                        xAxis: {
                            type: 'category',
                            // data: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']
                            data: respon.data['site_nearby_chart'][0],
                        },
                        yAxis: {
                            type: 'value'
                        },
                        series: [{
                            // data: [820, 932, 901, 934, 1290, 1330, 1320],
                            data: respon.data['site_nearby_chart'][1],
                            type: 'line'
                        }]
                    });
                }
            });

            $('button[name="check"]').on('click', function () {
                let data = new FormData();
                data.append('post_type', 'check');
                myajax({
                    url: '',
                    data: data,
                    success: function () {
                        console.log('success to send test_celery');
                    },
                });
            });

            $('button[name="export"]').on('click', function () {
                let data = new FormData();
                data.append('post_type', 'export');
                myajax({
                    url: '',
                    data: data,
                    success: function (respon) {
                        console.log(respon.data);
                        to_csv(respon.data, '结果.csv');
                    },
                });
            });
        });
    </script>
{% endblock script1 %}

{% block script_after %}
    {% include 'myinclude/basic/echarts.html' %}
{% endblock script_after %}