app/urls.py
from django.urls import path

from . import views

app_name = 'app'

urlpatterns = [
    path('', views.index, name='index'),
]

appipark/urls.py
from django.urls import path

from . import views

app_name = 'ipark'

urlpatterns = [
    # index
    path('', views.index, name='index'),

    # 素材管理
    path('material/list/<str:material_type>/', views.MaterialListView.as_view(), name='material_list'),
    path('material/<str:material_name>/', views.view_material, name='material_view'),

    # 节目分辨率
    path('program/scale_type/', views.ScaleTypeView.as_view(), name='scale_type'),

    # 节目管理
    path('program/list/', views.ProgramListView.as_view(), name='program_list'),
    path('program/new/<str:program_name>/<str:scale_type>/', views.ProgramNewView.as_view(), name='program_new'),
    path('program/<str:program_name>/', views.view_program, name='program_view'),
    path('program/edit/<str:program_name>/', views.ProgramEditView.as_view(), name='program_edit'),

    # 设备管理
    path('equipment/list/', views.EquipmentListView.as_view(), name='equipment_list'),
    path('equipment/programs/<str:equipment_name>/', views.EquipmentProgramListView.as_view(), name='equipment_program_list'),

    # 查询信息
    path('query/', views.QueryView.as_view(), name='query'),
]

project/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from django.views.static import serve

from project import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    # app
    path('', include('app.urls', namespace='app')),
    # npo
    path('npo/', include('appnpo.urls', namespace='npo')),
    # ipark
    path('ipark/', include('appipark.urls', namespace='ipark')),
    path('ipark1/', include('appipark1.urls', namespace='ipark1')),
    path('ipark2/', include('appipark2.urls', namespace='ipark2')),
    # 媒体文件
    re_path(r'media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
]

appipark/models.py
import re
from django.core.exceptions import ValidationError
from django.db import models
from .utils import myfunc


class MaterialType(models.Model):
    # 类型名称 唯一
    name = models.CharField(verbose_name='素材类型', max_length=20, unique=True)
    # 类型中文名 唯一
    name_zh = models.CharField(verbose_name='素材类型', max_length=20, unique=True)
    # 应用于input type=file的 accpt 参数 限制输入类型
    file_selector_accept = models.CharField(verbose_name='类型选择器', max_length=200)

    def __str__(self):
        return self.name


# 视频素材类
class Material(models.Model):
    # name 唯一
    name = models.CharField(verbose_name='素材名称', max_length=40, unique=True)
    # 素材类型 不使用外键，使用字段进行关联 type字段和MaterialType的name字段一致
    # type = models.ForeignKey(MaterialType, verbose_name='素材类型', on_delete=models.PROTECT)
    type = models.CharField(verbose_name='素材类型', max_length=20)
    # 素材文件
    file = models.FileField(verbose_name='素材文件', upload_to=myfunc.upload_to_file_path)
    # 素材缩略图
    thumbnail = models.ImageField(verbose_name='缩略图', upload_to=myfunc.upload_to_thumbnail_path)


# 节目分辨率
class ScaleType(models.Model):
    # name 唯一
    name = models.CharField(verbose_name='分辨率', max_length=20, unique=True)

    def clean(self):
        # 使用正则表达式检查name字段 必须是 正整数*正整数
        name_pattern = re.compile(r'^[1-9]\d*\*[1-9]\d*$')
        if name_pattern.match(self.name):
            super(ScaleType, self).clean()
        else:
            raise ValidationError('分辨率格式应为 宽*高 格式, 例: 1366*768')

    def __str__(self):
        return self.name


# 节目
class Program(models.Model):
    # name 唯一
    name = models.CharField(verbose_name='节目名称', max_length=40, unique=True)
    # 与 ScaleType name 字段对应
    scale_type = models.ForeignKey(ScaleType, on_delete=models.PROTECT, verbose_name='分辨率')
    #  文件路径
    path = models.CharField(max_length=200)
    # 存储空间--文件大小
    storage = models.FloatField(verbose_name='文件大小(M)')
    # 节目时长
    duration = models.IntegerField(verbose_name='播放时长(秒)')
    # 格式化以后的json
    json_input = models.CharField(max_length=2000)
    # 生成的ffmpegcmd
    ffmpegcmd = models.CharField(max_length=2000)


# 设备
class Equipment(models.Model):
    # name 唯一
    name = models.CharField(verbose_name='设备ID', max_length=40, unique=True)
    # 设备存储空间
    storage_all = models.FloatField(verbose_name='存储总量(M)')
    # 设备的可用存储空间
    storage_free = models.FloatField(verbose_name='可用存储(M)')
    # 设备安装位置
    location = models.CharField(verbose_name='设备位置', max_length=100)
    # 设备当前状态
    status = models.CharField(verbose_name='设备状态', max_length=40)
    # 轮播状态
    # wheel = models.CharField(verbose_name='轮播状态', max_length=20)
    wheel = models.BooleanField(verbose_name='轮播状态')
    # 播放开始时间
    start_time = models.CharField(verbose_name='开始时间', max_length=20)
    # 播放结束时间
    end_time = models.CharField(verbose_name='结束时间', max_length=20)


# 设备中的节目列表
class EquipmentProgram(models.Model):
    # 节目名称
    program = models.CharField(verbose_name='节目名称', max_length=40)
    # 设备id
    equipment = models.CharField(verbose_name='设备ID', max_length=40)
    # 在播放列表中的index -1 表示不在播放列表中
    index = models.IntegerField(verbose_name='列表序号')

    class Meta:
        unique_together = ['program', 'equipment']

appipark/forms.py
from django.forms import ModelForm

from . import models


class ScaleTypeForm(ModelForm):
    class Meta:
        model = models.ScaleType
        fields = '__all__'


class ProgramForm(ModelForm):
    class Meta:
        model = models.Program
        fields = ['name', 'scale_type']


class EquipmentForm(ModelForm):
    class Meta:
        model = models.Equipment
        fields = '__all__'

appipark/views.py
import os
import json

from django.shortcuts import render
from django.db.utils import IntegrityError

from . import models
from . import forms
from .utils.mydjango import MyView
from .utils import myfunc
from .utils import myffmpeg


def index(request):
    return render(request, 'appipark/index.html')


class MaterialListView(MyView):

    def get(self, request, material_type):
        material_types = models.MaterialType.objects.all()
        mtype = material_types.get(name=material_type)
        materials = models.Material.objects.filter(type=material_type)
        context = {
            # 当前的素材类型
            'material_type': material_type,
            # 输入类型限制
            'file_selector_accept': mtype.file_selector_accept,
            # 素材类型列表
            'material_types': material_types,
            # 当前类型的素材列表
            'materials': materials,
        }
        return render(request, 'appipark/material_list.html', context=context)

    def upload_files(self, request, material_type):
        result = {'errmsg': []}
        # 通过getilist方法可以直接获得列表
        list_files = request.FILES.getlist('files')
        list_materials = []
        for file in list_files:
            # 检查是否已存在同名文件
            query = models.Material.objects.filter(name=file.name)
            if query:
                result['errmsg'].append("{}--已存在同名文件".format(file.name))
            else:
                # 获取缩略图
                image = myfunc.get_thumbnail(file, material_type, (200, 150))
                # 生成material对象
                material = models.Material(name=file.name, type=material_type, file=file, thumbnail=image)
                list_materials.append(material)
        # 只有不存在任何err时 才进行保存
        if not result['errmsg']:
            for material in list_materials:
                material.save()
        return result

    def delete_material(self, request, material_type):
        result = {'errmsg': []}
        name = request.POST.get('name_to_delete')
        material = models.Material.objects.get(name=name)
        # 删除文件
        path = material.file.path
        os.remove(path)
        # 删除缩略图文件
        thumbnail = material.thumbnail.path
        os.remove(thumbnail)
        # 删除数据库记录
        material.delete()
        return result


# 素材预览页面
def view_material(request, material_name):
    context = {
        'material': models.Material.objects.get(name=material_name)
    }
    return render(request, 'appipark/material_view.html', context=context)


# 节目预览页面
def view_program(request, program_name):
    program = models.Program.objects.get(name=program_name)
    context = {
        'program': program.path
    }
    return render(request, 'appipark/program_view.html', context=context)


# 节目分辨率
class ScaleTypeView(MyView):

    def get_form_info(self, request):
        result = {
            'errmsg': [],
            'form': forms.ScaleTypeForm().as_ul()
        }
        return result

    def add_scale_type(self, request):
        result = {'errmsg': []}
        scale_type = forms.ScaleTypeForm(request.POST)
        if scale_type.is_valid():
            scale_type.save()
        else:
            for err in scale_type.errors:
                result['errmsg'].append(scale_type.errors[err])
        return result


class ProgramListView(MyView):

    def get(self, request):
        context = {
            'programs': models.Program.objects.all()
        }
        return render(request, 'appipark/program_list.html', context=context)

    def delete_program(self, request):
        result = {'errmsg': []}
        program_name = request.POST.get('program_name')
        program = models.Program.objects.get(name=program_name)
        # 删除硬盘文件
        os.remove(program.path)
        # 删除数据库记录
        program.delete()
        return result


# 新建节目view
class ProgramNewView(MyView):

    def get(self, request, program_name, scale_type):
        # 节目初始名称
        context = {'program_name': program_name}
        # 获取分辨率 宽度和高度 单位是px像素
        scale_type = models.ScaleType.objects.get(id=scale_type)
        size = scale_type.name.split('*')
        context['scale_type'] = scale_type.name
        context['width'] = size[0]
        context['height'] = size[1]
        return render(request, 'appipark/program_new.html', context=context)

    def get_form_info(self, request, program_name, scale_type):
        result = {
            'errmsg': [],
            'form': forms.ProgramForm().as_ul()
        }
        return result

    def save_program(self, request, program_name, scale_type):
        result = {'errmsg': []}
        # 获取提交上来的节目信息
        program = request.POST.get('program')
        program = json.loads(program)
        # 分辨率
        scale = models.ScaleType.objects.get(id=scale_type)
        scale_size = scale.name.split('*')
        material_list = models.Material.objects.all()
        # 背景图片
        bg_image = None
        if program['bg_image']:
            bg_image = material_list.get(name=program['bg_image']['name'])
            # 格式化myffmpeg的输入
            myffmpeg_in = {
                'duration': program['duration'],
                'size': {'width': scale_size[0], 'height': scale_size[1]},
                'bg_image': bg_image.file.path,
                'bg_image_name': bg_image.name,
                'bg_image_url': bg_image.file.url,
                'groups': [],
            }
        else:
            myffmpeg_in = {
                'duration': program['duration'],
                'size': {'width': scale_size[0], 'height': scale_size[1]},
                'bg_image': None,
                'bg_image_name': None,
                'bg_image_url': None,
                'groups': [],
            }
        for group in program['groups']:
            grp = {
                'size': group['size'],
                'position': group['position'],
                'duration': {'start': group['duration']['start'], 'end': group['duration']['start'] + group['duration']['duration']},
                'inputs': [],
            }
            # material_start = 0
            # material_end = 0
            for material in group['materials']:
                mt = material_list.get(name=material['name'])
                # material_end = material_start + material['duration']
                inp = {
                    'name': mt.name,
                    'path': mt.file.path,
                    'url': mt.file.url,
                    'type': material['type'],
                    # start 是0 end是duration  此时未考虑从中间截取视频，视频都是从0s开始截取
                    'duration': {'start': 0, 'end': material['duration']}
                }
                grp['inputs'].append(inp)
                # material_start = material_end
            myffmpeg_in['groups'].append(grp)
        # 输出路径
        name = program['name']
        # 输出文件夹路径
        outpath = os.path.join('media', 'appipark', 'program')
        # 如果文件夹不存在 则创建文件夹
        if not os.path.exists(outpath):
            os.makedirs(outpath)
        # 输出文件路径
        outpath = os.path.join(outpath, '{}.mp4'.format(name))
        try:
            ffmpeg_cmd = myffmpeg.run_myffmpeg(myffmpeg_in, outpath)
        except AttributeError:
            result['errmsg'].append('ffmpeg处理视频时执行错误。')
        else:
            models.Program(name=name, scale_type=scale, path=outpath, storage=myfunc.get_file_storage_size(outpath), duration=program['duration'], json_input=json.dumps(myffmpeg_in), ffmpegcmd=ffmpeg_cmd).save()
        return result


# 从服务器获取信息
class QueryView(MyView):

    def query_materials(self, request):
        result = {
            'errmsg': [],
            'materials': {},
        }
        # 获取要查询的类型
        material_types = request.POST.get('material_type')
        material_types = material_types.split('&&')
        # 全部类型
        types = models.MaterialType.objects.all()
        # 全部素材
        materials = models.Material.objects.all()
        # 分类型处理
        for type_name in material_types:
            material_type = types.get(name=type_name)
            materials_of_type = materials.filter(type=material_type)
            # 使用列表推导
            result['materials'][type_name] = [
                {
                    'name': material.name,
                    'url': material.file.url,
                    'type': material.type,
                 } for material in materials_of_type
            ]
        return result

    def query_programs(self, request):
        result = {
            'errmsg': [],
            'programs': [],
        }
        programs = models.Program.objects.all()
        for program in programs:
            result['programs'].append({
                'name': program.name,
                'url': program.path,
                'storage': program.storage,
            })
        return result


# 编辑节目
class ProgramEditView(MyView):

    def get(self, request, program_name):
        context = {'program_name': program_name}
        # 节目
        program = models.Program.objects.get(name=program_name)
        scale_type = program.scale_type
        size = scale_type.name.split('*')
        context['scale_type'] = scale_type.name
        context['width'] = size[0]
        context['height'] = size[1]
        context['duration'] = program.duration
        return render(request, 'appipark/program_edit.html', context=context)

    def get_program_json(self, request, program_name):
        result = {'errmsg': []}
        program = models.Program.objects.get(name=program_name)
        result['json'] = program.json_input
        return result

    def save_program(self, request, program_name):
        result = {'errmsg': []}
        # 获取提交上来的节目信息
        program = request.POST.get('program')
        program = json.loads(program)
        # 分辨率
        s_program = models.Program.objects.get(name=program_name)
        # 删除原文件
        if os.path.exists(s_program.path):
            os.remove(s_program.path)
        scale = s_program.scale_type
        scale_size = scale.name.split('*')

appipark/templates/appipark/base.html
{% load static %}
<!DOCTYPE html>
<html lang="zh">
    <head>
        {# page_hea块 有些模块（如百度地图）需要放在jquery之前导入，某则会出错，可以放在这个模块当中 #}
        {% block page_head %}{% endblock %}
        {# jquery #}
        <script src="{% static 'jquery/jquery-3.5.1.min.js' %}"></script>
        {# jquery-ui #}
        <script src="{% static 'jquery-ui/jquery-ui.min.js' %}"></script>
        <link rel="stylesheet" href="{% static 'jquery-ui/jquery-ui.min.css' %}">
        {# popper 是bootstrap4一些功能的前置 #}
        <script src="{% static 'popper/popper.js' %}"></script>
        {# bootstrap4 #}
        <link rel="stylesheet" href="{% static 'bootstrap-4.5.0-dist/css/bootstrap.css' %}">
        <script src="{% static 'bootstrap-4.5.0-dist/js/bootstrap.js' %}"></script>
        {# layer 弹窗插件 #}
        <script src="{% static 'layer/layer.js' %}"></script>

        {# 自定义的base.js #}
        <script src="{% static 'appipark/base.js' %}"></script>

        {# 解决 Not Found: /favicon.ico #}
        <link REL="SHORTCUT ICON" HREF="{% static 'img/fjthcc.ico' %}" />
        {% if title%}
            <title>{{ title }}</title>
        {% endif %}
    </head>
    <body>
        {# page_body块 页面主要内容 #}
        {% block page_body %}{% endblock %}
        {# csrf_token #}
        <div>{% csrf_token %}</div>
        {# page_script块 页面脚本 #}
        {% block page_script %}{% endblock %}
    </body>
</html>

appipark/templates/appipark/equipment_program_list.html
{% extends 'appipark/base.html' %}
{% load get_dict_item %}

{% block page_body %}
<div class="container-fluid col-11 mt-3">
    <div class="row">
        <div class="input-group col-6 mt-2 pl-0">
            <div class="input-group-prepend">
                <span class="input-group-text">设备ID</span>
            </div>
            <input type="text" class="form-control" readonly value="{{ equipment.name }}" name="equipment_name">
        </div>
        <div class="input-group col-6 mt-2 pl-0">
            <div class="input-group-prepend">
                <span class="input-group-text">存储空间</span>
            </div>
            <input type="text" class="form-control" readonly value="总计{{ equipment.storage_all }}M/可用{{ equipment.storage_free }}M">
        </div>
        <div class="input-group col-6 mt-2 pl-0">
            <div class="input-group-prepend">
                <span class="input-group-text">设备安装位置</span>
            </div>
            <input type="text" class="form-control" readonly value="{{ equipment.location }}">
        </div>
        <div class="input-group col-6 mt-2 pl-0">
            <div class="input-group-prepend">
                <span class="input-group-text">设备状态</span>
            </div>
            <input type="text" class="form-control" readonly value="{{ equipment.status }}">
        </div>
        <div class="input-group col-6 mt-2 pl-0">
            <div class="input-group-prepend">
                <span class="input-group-text">轮播开关</span>
            </div>
            {% if equipment.wheel %}
                <input type="text" class="form-control" readonly value="打开" name="wheel_status">
                <div class="input-group-append">
                    <button class="btn btn-primary" name="change_wheel_status">关闭轮播</button>
                </div>
            {% else %}
                <input type="text" class="form-control" readonly value="关闭">
                <div class="input-group-append">
                    <button class="btn btn-primary" name="change_wheel_status">打开轮播</button>
                </div>
            {% endif %}
        </div>
        <div class="input-group col-6 mt-2 pl-0">
            <div class="input-group-prepend">
                <span class="input-group-text">播放时间</span>
            </div>
            <input type="text" class="form-control" readonly value="{{ equipment.start_time }}-{{ equipment.end_time }}">
            <div class="input-group-append">
                <button class="btn btn-primary" name="set_play_time">修改播放时间</button>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="container-fluid">
            <div class="row mt-2">
                <button class="btn btn-primary" name="send_program_to_equipment">推送节目</button>
                <button class="btn btn-primary" name="send_program_to_equipment">立即播放</button>
            </div>
            <div class="row mt-2">
                <table class="table table-striped">
                    <thead class="thead-dark">
                        <tr>
                            <th scope="col">节目名称</th>
                            <th scope="col">分辨率</th>
                            <th scope="col">播放时长</th>
                            <th scope="col">文件大小(M)</th>
                            <th scope="col">是否在播放列表</th>
                            <th scope="col">操作</th>
                        </tr>
                    </thead>
                    {% for program in programs %}
                        <tr>
                            <td>{{ program|get_item:"name" }}</td>
                            <td>{{ program|get_item:"scale_type" }}</td>
                            <td>{{ program|get_item:"duration" }}</td>
                            <td>{{ program|get_item:"storage" }}</td>
                            {% if program|get_item:"index" == -1 %}
                                <td>否</td>
                                <td>
                                    <a class="btn btn-link" href="{% url 'ipark:program_view' program|get_item:"name" %}">预览</a>
                                    <button class="btn btn-link" name="delete_program_from_equipment" obj_name="{{ program|get_item:"name" }}">从设备上移除</button>
                                    <button class="btn btn-link" name="add_program_to_play_list" obj_name="{{ program|get_item:"name" }}">添加到播放列表</button>
                                </td>
                            {% else %}
                                <td>是</td>
                                <td>
                                    <a class="btn btn-link" href="{% url 'ipark:program_view' program|get_item:"name" %}">预览</a>
                                    <button class="btn btn-link" name="delete_program_from_equipment" obj_name="{{ program|get_item:"name" }}">从设备上移除</button>
                                    <button class="btn btn-link" name="delete_program_from_play_list" obj_name="{{ program|get_item:"name" }}">移出播放列表</button>
                                </td>
                            {% endif %}
                        </tr>
                    {% empty %}
                        暂未推送节目到设备
                    {% endfor %}
                </table>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block page_script %}
<script>
// 推送
$(document).on('click', 'button[name="send_program_to_equipment"]', function () {
    let post_data = get_formdata('query_programs');
    myajax('{% url "ipark:query" %}', post_data, function (respon) {
        if (respon.programs.length === 0) {
            layer.msg('没有可供推送的节目');
        } else {
            let title = '推送节目到设备';
            let content = get_content_of_programs(respon.programs);
            let index_modal = show_modal(title, content, function () {
                layer.close(index_modal);
                let post_data = get_formdata('send_program_to_equipment');
                let $input = $('input[name="program_obj"]:checked');
                for (inp of $input) {
                    post_data.append('program_name', $(inp).attr('obj_name'))
                }
                myajax('', post_data, function () {
                    window.location.href = '';
                });
            });
        }
    });
});

function get_content_of_programs(programs) {
    const ul_fmt = '<ul class="list-group">{0}</ul>';
    const checkbox_input_li_fmt = '<li class="list-group-item"><input type="checkbox" name="program_obj" obj_name="{0}">{0}</li>';
    let arr_lis = [];
    for (program of programs) {
        arr_lis.push(checkbox_input_li_fmt.format(program.name));
    }
    return ul_fmt.format(arr_lis.join(''));
}

// 从设备上移除节目
$(document).on('click', 'button[name="delete_program_from_equipment"]', function () {
    let program_name = $(this).attr('obj_name');
    let equipment_name = $('input[name="equipment_name"]').val();
    layer.confirm('确定要从 "{0}" 设备上删除节目 "{1}"'.format(equipment_name, program_name), function () {
        let post_data = get_formdata('delete_program_from_equipment');
        post_data.append('program_name', program_name);
        myajax('', post_data, function () {
            window.location.href = '';
        });
    });
});

// 修改轮播状态
$(document).on('click', 'button[name="change_wheel_status"]', function () {
    let wheel_status = $('input[name="wheel_status"]').val();
    let post_data = get_formdata('change_wheel_status');
    myajax('', post_data, function () {
        window.location.href = '';
    });
});

// 添加到播放列表
$(document).on('click', 'button[name="add_program_to_play_list"]', function () {
    let program_name = $(this).attr('obj_name');
    let post_data = get_formdata("add_program_to_play_list");
    post_data.append('program_name', program_name);
    myajax('', post_data, function () {
        window.location.href = '';
    });
});

// 移除播放列表
$(document).on('click', 'button[name="delete_program_from_play_list"]', function () {
    let program_name = $(this).attr('obj_name');
    let post_data = get_formdata("delete_program_from_play_list");
    post_data.append('program_name', program_name);
    myajax('', post_data, function () {
        window.location.href = '';
    });
});

// 修改播放时间
$(document).on('click', 'button[name="set_play_time"]', function () {
    let title = '修改播放时间';
    let content = '<form name="set_play_time" class="form-group mt-2"><div class="input-group"><div class="input-group-prepend"><span class="input-group-text">开始时间</span></div><input type="text" class="form-control" name="time_start"></div><div class="input-group"><div class="input-group-prepend"><span class="input-group-text">结束时间</span></div><input type="text" class="form-control" name="time_end"></div></form>';
    show_modal(title, content, function () {
        let post_data = get_formdata('set_play_time');
        myajax('', post_data, function () {
            window.location.href = '';
        });
    });
});
</script>
{% endblock %}

appipark/templates/appipark/index.html
{% load static %}
<!DOCTYPE html>
<html lang="zh">
<head>
    <meta charset="UTF-8">
    <link REL="SHORTCUT ICON" HREF="{% static 'img/fjthcc.ico' %}" />
    <script src="{% static 'utils/jquery/jquery-3.4.1.min.js' %}"></script>
    <script src="{% static 'utils/popper/popper.js' %}"></script>
    <link rel="stylesheet" href="{% static 'utils/bootstrap4/css/bootstrap.css' %}">
    <script src="{% static 'utils/bootstrap4/js/bootstrap.js' %}"></script>
    {% if title%}
    <title>{{ title }}</title>
    {% endif%}
</head>
<body>
<div class="container-fluid col-5 mt-3">
    <h1>appipark.index</h1>
</div>
<div class="container-fluid col-5 mt-3">
    <ul class="list-group">
        <li class="list-group-item"><a href="{% url 'ipark:material_list' 'video' %}">素材列表-视频</a></li>
        <li class="list-group-item"><a href="{% url 'ipark:program_list' %}">节目列表</a></li>
        <li class="list-group-item"><a href="{% url 'ipark:equipment_list' %}">设备列表</a></li>
    </ul>
</div>
</body>
</html>

appipark/templates/appipark/material_view.html
<!DOCTYPE html>
<html lang="zh" style="height: 100%; margin: 0;">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width,initial-scale=1.0" />
    </head>
    <body style="height: 100%; margin: 0;">
    {% if material.type == 'video' %}
        <video style="max-width: 100%; max-height: 100%; display: block;" src="{{ material.file.url }}" controls="controls">您的浏览器不支持 video 标签。</video>
    {% elif material.type == 'image' %}
        <img style="max-width: 100%; max-height: 100%; display: block;" src="{{ material.file.url }}" alt="图片逃跑了。">
    {% endif %}
    </body>
</html>

appipark/templates/appipark/program_list.html
{% extends 'appipark/base.html' %}

{% block page_body %}
<div class="container-fluid">
    <div class="row col-11 mt-3">
        {# 新增节目 #}
        <button type="button" class="btn btn-primary" name="new_program">新增节目</button>
        {# 新增分辨率 #}
        <button type="button" class="btn btn-primary" name="add_scale_type">新增分辨率</button>
    </div>
    <div class="row col-11 mt-3">
        <table class="table table-striped">
            <thead class="thead-dark">
                <tr>
                    <th scope="col">节目名称</th>
                    <th scope="col">分辨率</th>
                    <th scope="col">播放时长</th>
                    <th scope="col">文件大小(M)</th>
                    <th scope="col">操作</th>
                </tr>
            </thead>
            <tbody>
                {% for program in programs%}
                    <tr>
                        <td>{{ program.name }}</td>
                        <td>{{ program.scale_type.name }}</td>
                        <td>{{ program.duration }}</td>
                        <td>{{ program.storage }}</td>
                        <td>
                            <a class="btn btn-link" href="{% url 'ipark:program_view' program.name %}">预览</a>
                            <button class="btn btn-link" name="edit_program" objname="{{ program.name }}">编辑</button>
                            <button class="btn btn-link" name="delete_program" objname="{{ program.name }}">删除</button>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

{% block page_script %}
<script>
// 新增分辨率
$(document).on('click', 'button[name="add_scale_type"]', function () {
    // 从服务器获取form信息
    let post_data = get_formdata('get_form_info');
    myajax('{% url "ipark:scale_type" %}', post_data, function (respon) {
        // 弹窗显示新增分辨率表单
        let title = '新增节目分辨率';
        let post_type = 'add_scale_type';
        let content = get_form_content(post_type, respon.form);
        show_modal(title, content, function () {
            let post_data = get_formdata(post_type);
            myajax('{% url "ipark:scale_type" %}', post_data, function () {
                window.location.href = '';
            });
        });
    });
});

// 新增节目
$(document).on('click', 'button[name="new_program"]', function () {
    // 获取节目的form
    let post_data = get_formdata('get_form_info');
    myajax('{% url "ipark:program_new" 'a' 1 %}', post_data, function (respon) {
        // 新增节目弹窗
        let title = '新增节目';
        let type = 'add_program';
        let content = get_form_content(type, respon.form);
        show_modal(title, content, function () {
            let data = get_formdata(type);
            let name = data.get('name');
            let scale_type = data.get('scale_type');
            window.location.href = "/ipark1/program/new/{0}/{1}/".format(name, scale_type);
        });
    });
});

// 删除节目
$(document).on('click', 'button[name="delete_program"]', function () {
    let program_name = $(this).attr('objname');
    layer.confirm('确定要删除{0}?'.format(program_name), function () {
        let post_data = get_formdata('delete_program');
        post_data.append('program_name', program_name);
        myajax('', post_data, function (respon) {
            window.location.href = '';
        });
    });
});

// 编辑节目
$(document).on('click', 'button[name="edit_program"]', function () {
    let program_name = $(this).attr('objname');
    window.location.href = '/ipark1/program/edit/{0}'.format(program_name);
});
</script>
{% endblock %}