app/urls.py
from django.urls import path

from . import views

app_name = 'app'

urlpatterns = [
    path('', views.index, name='index'),
]

appipark1/urls.py
from django.urls import path

from . import views

# 定义url命名空间
app_name = 'ipark1'

urlpatterns = [
    # 主页
    path('', views.index, name='index'),

    # 登录页
    path('login/', views.Login.as_view(), name='login'),

    # 注销
    path('logout/', views.logout, name='logout'),

    # 实时监控
    path('fr/monitor/', views.frindex, name='monitor'),
    # 黑名单
    path('fr/blacklist/', views.BlacklistView.as_view(), name='blacklist'),
    # 黑名单抓拍记录
    path('fr/blacklist/record', views.RecordView.as_view(), name='record'),
    # 黑名单标签
    path('fr/blacklist/tag/', views.TagView.as_view(), name='tag'),
    # 设备管理
    path('fr/equipment/', views.EquipmentView.as_view(), name='equipment'),

    #  抓拍照片上传
    path('zhuapai/', views.zhuapai, name='zhuapai'),
]

project/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from django.views.static import serve

from project import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    # app
    path('', include('app.urls', namespace='app')),
    # npo
    path('npo/', include('appnpo.urls', namespace='npo')),
    # ipark
    path('ipark/', include('appipark.urls', namespace='ipark')),
    path('ipark1/', include('appipark1.urls', namespace='ipark1')),
    path('ipark2/', include('appipark2.urls', namespace='ipark2')),
    # 媒体文件
    re_path(r'media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
]

appipark1/models.py
from django.db import models


class Tag(models.Model):
    name = models.CharField(max_length=40, null=False)
    comment = models.CharField(max_length=400, default='')
    isdelete = models.BooleanField(default=False)


class Equipment(models.Model):
    name = models.CharField(max_length=40, null=False)
    type = models.CharField(max_length=40, null=False)
    location = models.CharField(max_length=400, default='')
    state = models.CharField(max_length=10, default='')
    isdelete = models.BooleanField(default=False)


class Blacklist(models.Model):
    photo = models.CharField(max_length=100, null=False)
    comment = models.CharField(max_length=400, default='')
    tag = models.CharField(max_length=40, null=False)
    face_id = models.CharField(max_length=32, null=False)
    face_token = models.CharField(max_length=32, null=False)
    isdelete = models.BooleanField(default=False)


class Record(models.Model):
    img = models.CharField(max_length=100, null=False)
    photo = models.CharField(max_length=100, null=False)
    tag = models.CharField(max_length=40, null=False)
    face_id = models.CharField(max_length=32, null=False)
    score = models.FloatField(null=False)
    record_time = models.DateTimeField(null=False)
    equipment = models.CharField(max_length=40, null=False)
    isdelete = models.BooleanField(default=False)


class Task(models.Model):
    pass

appipark1/views.py
import traceback
import json
import base64
from os import path
from datetime import datetime
from django.shortcuts import render, HttpResponse, redirect
from django.views import View
from django.contrib import auth
from django.views.decorators.csrf import csrf_exempt
# from django.utils.decorators import method_decorator
# from django.contrib.auth.decorators import login_required
from .utils.pager import Pager
from .utils.baiduFace import face_add, face_del, face_search
from .utils import myutils
from . import models
from project import settings


class MyView(View):
    query_info = {}  # 页面传送的查询参数
    query_dict = {}  # 传递给filter的参数字典  与上面的区别在于对字符串字段添加了模糊查询
    current_page = 1  # 当前页码
    per_page = 20  # 每页显示数量
    deleted_visible = False  # 是否显示已删除

    # @method_decorator(login_required())

    def dispatch(self, request, *args, **kwargs):
        print('enter MyView.dispatch', request.method)
        return super(MyView, self).dispatch(request, *args, **kwargs)

    def post(self, request):
        post_type = request.POST.get('post_type')
        print('enter MyView.post', request.method, post_type)
        if post_type == 'add':
            return self.add_obj(request)
        elif post_type == 'get':
            return self.get_obj(request)
        elif post_type == 'edit':
            return self.edit_obj(request)
        elif post_type == 'delete':
            return self.delete_obj(request)
        elif post_type == 'recover':
            return self.recover_obj(request)
        elif post_type == 'delete_some':
            return self.delete_some(request)
        elif post_type == 'query':
            return self.query_obj(request)
        elif post_type == 'show_page':
            return self.show_page(request)
        elif post_type == 'change_deleted_visible':
            return self.change_deleted_visible(request)
        else:
            return HttpResponse(
                'post_type “{0}” 不合法，请联系管理员修复BUG！'.format(post_type))

    def add_obj(self, request):
        print('enter MyView.add_obj', request.POST)
        return HttpResponse('是不是忘记重写add_obj')

    def get_obj(self, request):
        print('enter MyView.get_obj', request.POST)
        return HttpResponse('是不是忘记重写get_obj')

    def edit_obj(self, request):
        print('enter MyView.edit_obj', request.POST)
        return HttpResponse('是不是忘记重写edit_obj')

    def delete_obj(self, request):
        print('enter MyView.delete_obj', request.POST)
        return HttpResponse('是不是忘记重写delete_obj')

    def recover_obj(self, request):
        print('enter MyView.recover_obj', request.POST)
        return HttpResponse('是不是忘记重写recover_obj')

    def delete_some(self, request):
        print('enter MyView.delete_some', request.POST)
        return HttpResponse('是不是忘记重写delete_some')

    def query_obj(self, request):
        print('enter MyView.query_obj', request.POST)
        return HttpResponse('是不是忘记重写query_obj')

    def show_page(self, request):
        print('enter TestView.show_page', request.POST)
        try:
            MyView.current_page = request.POST.get('current_page')
            MyView.per_page = request.POST.get('per_page')
            return HttpResponse('OK')
        except Exception as err:
            traceback.print_exc()
            return HttpResponse(repr(err))

    def change_deleted_visible(self, request):
        print('enter MyView.change_deleted_visible', request.POST)
        try:
            b = request.POST.get('deleted_visible')
            if b == 'False':
                MyView.deleted_visible = False
            else:
                MyView.deleted_visible = True
            print(MyView.deleted_visible)
            return HttpResponse('OK')
        except Exception as err:
            traceback.print_exc()
            return HttpResponse(repr(err))


class BlacklistView(MyView):
    def get(self, request):
        if self.deleted_visible:
            print(self.deleted_visible, True)
            obj_list = models.Blacklist.objects.filter(**self.query_dict)
        else:
            print(self.deleted_visible, False)
            obj_list = models.Blacklist.objects.filter(isdelete=False).filter(
                **self.query_dict)
        # 分页
        pager = Pager(current_page=BlacklistView.current_page,
                      total_items=obj_list.count(),
                      per_page=BlacklistView.per_page)
        obj_list = obj_list[pager.start():pager.end()]
        # 给返回数据添加网页标题
        data = {
            'title': 'test',
            'obj_list': obj_list,
            'pager': pager,
        }
        # 把筛选条件加到返回的obj中
        data.update(BlacklistView.query_info)
        data.update({'deleted_visible': BlacklistView.deleted_visible})
        return render(request, 'appipark1/blacklist.html', data)

    def add_obj(self, request):
        print('enter BlacklistView.add_obj', request.POST)
        try:
            # # 获取上传的文件并存储到media目录
            file = request.FILES.get('uploadfile')
            # # 存储前先获取一个不重复的face_id, 这个id同时作为存储在服务器上的文件名
            # face_id = myutils.get_unique_str()
            # name = face_id + '.' + file.name.split('.')[-1]
            # file_path = path.join(settings.MEDIA_ROOT, 'blacklist', name)
            # with open(file_path, 'wb') as f:
            #     for i in file.chunks():
            #         f.write(i)
            # print(file_path, '---已保存')
            if file:
                result = myutils.save_uploadfile(file)
                # 发送到百度并获取face_token
                face_add_result = face_add(result['file_path'], 'blackList',
                                           result['face_id'])
                if face_add_result['error_msg'] == 'SUCCESS':
                    obj = models.Blacklist(
                        photo=result['photo'],
                        tag=request.POST.get('tag'),
                        comment=request.POST.get('comment'),
                        face_id=result['face_id'],
                        face_token=face_add_result['face_token'],
                        isdelete=False,
                    )
                    obj.save()
                    return HttpResponse('OK')
                else:
                    return HttpResponse(face_add_result['error_msg'])
            else:
                return HttpResponse('uploadfile 不存在！')
        except Exception as e:
            traceback.print_exc()
            return HttpResponse(repr(e))

    def get_obj(self, request):
        try:
            obj_id = request.POST.get('id')
            obj = models.Blacklist.objects.get(id=obj_id)
            # 返回数据添加class属性
            data = {'class': 'blacklist'}
            # 将obj的自有属性添加到返回数据data
            data.update(myutils.todict(obj))
            # 返回数据data转换成json数据
            data = json.dumps(data)
            return HttpResponse(data)
        except Exception as e:
            # 打印报错
            traceback.print_exc()
            return HttpResponse(repr(e))

    def edit_obj(self, request):
        try:
            obj_id = request.POST.get('id')
            obj = models.Blacklist.objects.get(id=obj_id)
            # 此处需要修改图片信息， 并修改百度列表中 的信息
            # 获取上传的文件并存储到media目录
            file = request.FILES.get('uploadfile')
            if file:
                # # 存储前先获取一个不重复的face_id, 这个id同时作为存储在服务器上的文件名
                # face_id = myutils.get_unique_str()
                # name = face_id + '.' + file.name.split('.')[-1]
                # file_path = path.join(settings.MEDIA_ROOT, 'blacklist', name)
                # with open(file_path, 'wb') as f:
                #     for i in file.chunks():
                #         f.write(i)
                # print(file_path, '---已保存')
                result = myutils.save_uploadfile(file)
                # 发送到百度并获取face_token
                face_add_result = face_add(result['file_path'], 'blackList',
                                           result['face_id'])
                if face_add_result['error_msg'] == 'SUCCESS':
                    obj.face_token = face_add_result['face_token']
                    obj.face_id = result['face_id']
                    obj.photo = result['photo']
                    obj.tag = request.POST.get('tag')
                    obj.comment = request.POST.get('comment')
                    obj.save()
                    return HttpResponse('OK')
                else:
                    return HttpResponse(face_add_result['error_msg'])
            else:
                obj.tag = request.POST.get('tag')
                obj.comment = request.POST.get('comment')
                obj.save()
                return HttpResponse('OK')
        except Exception as e:
            traceback.print_exc()
            return HttpResponse(repr(e))

    def delete_obj(self, request):
        print('enter BlacklistView.delete_obj', request.POST)
        try:
            # 此处需要删除百度list的图片
            obj_id = request.POST.get('id')
            obj = models.Blacklist.objects.get(id=obj_id)
            # 发送给百度并删除
            face_del_result = face_del(group_id='blackList',
                                       face_token=obj.face_token,
                                       user_id=obj.face_id)
            print(face_del_result)
            if face_del_result['error_msg'] == 'SUCCESS':
                obj.face_token = ''
                obj.isdelete = True
                obj.save()
                return HttpResponse('OK')
            else:
                print(face_del_result['error_msg'])
                return HttpResponse(face_del_result['error_msg'])
        except Exception as e:
            traceback.print_exc()
            return HttpResponse(repr(e))

    def recover_obj(self, request):
        print('enter BlacklistView.recover_obj', request.POST)
        try:
            # 需要重新将图片发送给百度并注册face_token
            obj_id = request.POST.get('id')
            obj = models.Blacklist.objects.get(id=obj_id)

appipark1/templates/appipark1/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {# 使用bootstrap4必须添加这一段 #}
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    {# 引入bootstrap4 #}
    <link rel="stylesheet" href="{% static 'bootstrap-4.5.0-dist/css/bootstrap.css' %}">
    {# 引入自定义stryle #}
    <link rel="stylesheet" href="{% static 'appipark1/base/base.css' %}">
    {# 引入jquery 一般在最前面引入，很多js会以jquery为基础 #}
    <script src="{% static 'jquery/jquery-3.5.1.min.js' %}"></script>
    {# 引入popper 必须在bootstrap.js之前引入 #}
    <script src="{% static 'popper/popper.js' %}"></script>
    {# 引入layer #}
    <script src="{% static 'layer/layer.js' %}"></script>
    {# 引入bootstrap #}
    <script src="{% static 'bootstrap-4.5.0-dist/js/bootstrap.js' %}"></script>
    {# 引入自定义js #}
    <script src="{% static 'appipark1/base/base.js' %}"></script>
{% block style %}
    {# 临时性css #}
{% endblock %}
{% block script %}
    {# 页面独立js和临时性js #}
{% endblock %}
    <title>{{ title }}</title>
</head>
<body>
<div id="top">
    <nav class="navbar navbar-expand-md page-head navbar-dark">
        <a class="nav-link page-head-logo" href="{% url 'ipark1:index' %}">福建天海通信ipark</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#topnavbars" aria-controls="topnavbars" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="topnavbars">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'ipark1:monitor' %}">监控管理</a>
                </li>
            </ul>
            {# 用户操作，欢迎和注销 #}
            <ul class="navbar-nav">
                <li>欢迎，{{ username }}</li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'ipark1:logout' %}">注销</a>
                </li>
            </ul>
        </div>
    </nav>
</div>
{# 内容block #}
{% block pgbody1 %}
<div>
    <div>左侧</div>
    <div>右侧</div>
</div>
{% endblock %}
</body>
</html>

appipark1/templates/appipark1/base_monitor.html
{% extends 'appipark1/base.html' %}

{% block pgbody1 %}
{# 整体 #}
<div>
{# 左侧边导航栏 #}
    <div id="left-menu" class="container-fluid col-12 col-md-2 float-md-left">
        <div class="row">
            <nav class="">
                <ul class="nav d-block">
                    <li class="nav-item"><a class="nav-link" href="{% url 'ipark1:record' %}">抓拍记录</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'ipark1:blacklist' %}">黑名单管理</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'ipark1:tag' %}">黑名单标签</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'ipark1:equipment' %}">设备管理</a></li>
                </ul>
            </nav>
        </div>
    </div>
    {% block pgbody2 %}
        <div id="right-body" class="container-fluid col-12 col-md-10 float-md-right">右侧</div>
    {% endblock %}
</div>
{% endblock %}

appipark1/templates/appipark1/blacklist.html
{% extends 'appipark1/base_monitor.html' %}

{% block pgbody2 %}
<div class="container-fluid  col-12 col-md-10 float-md-right">
    {# 查询 #}
    <div class="row p-3 ">
        <label>查询条件(支持模糊查询)：</label>
        <label>
            <input type="text" placeholder="标签名称" class="mr-5" id="query_name" value="{{ name }}" >
        </label>
        <button type="button" class="btn btn-primary query_button">查询</button>
    </div>
    {# 新增/批量删除等按钮 #}
    <div class="row p-3">
        <button type="button" class="btn btn-primary mr-3" id="add-obj">新增</button>
        <button type="button" class="btn btn-light mr-auto" id="delete-some">批量删除</button>
        {% if deleted_visible %}
        <button type="button" class="btn btn-light mr-3 change-deleted_visible" value='False'>不显示已删除</button>
        {% else %}
        <button type="button" class="btn btn-light mr-3 change-deleted_visible" value='True'>显示已删除</button>
        {% endif %}
    </div>
    {# 表格形式展示内容 #}
    <div class="row p-3">
        <table class="table table-striped">
            {# 表头 #}
            <tr>
            <td>
                <label for="select_all"></label>
                <input type="checkbox" value="all" id="select_all" >
            </td>
            <td>序号</td>
            <td>照片</td>
            <td>标签</td>
            <td>备注</td>
            <td>操作</td>
            </tr>
            {# 表格内容 #}
            {% for obj in obj_list %}
            <tr>
            <td>
                <label>
                    <input class="checkbox" type="checkbox" name="table_checkbox" value="{{ obj.id }}">
                </label>
            </td>
            {# 序号 #}
            <td>{{ forloop.counter }}</td>
            {# 照片 #}
            <td>
                <img src="{{ MEDIA_URL }}{{ obj.photo }}" alt="">
            </td>
            {# 标签 #}
            <td>{{ obj.tag }}</td>
            <td>{{ obj.comment }}</td>
            {% if obj.isdelete %}
            <td>
                <button type="button" class="btn btn-link edit-obj">编辑</button>
                <button type="button" class="btn btn-link recover-obj">恢复</button>
            </td>
            {% else %}
            <td>
                <button type="button" class="btn btn-link edit-obj">编辑</button>
                <button type="button" class="btn btn-link delete-obj">删除</button>
            </td>
            {% endif %}
            </tr>
            {% endfor %}
        </table>
    </div>
    {# 分页 #}
    <div class="row pl-3">
        <div id="pager" class="float-right">
            <nav aria-label="Page navigation">
                <ul class="pagination" per_page={{ pager.per_page|safe }}>
                    {# 页面信息 #}
                    {{ pager.pager|safe }}
                </ul>
            </nav>
        </div>
    </div>
</div>
{% endblock pgbody2 %}

{% block script %}
<script>
//定义query时传送给服务器的消息
function get_query_str() {
    //从当前网页获取query_info
    //每条属性之间以****分割符间隔开， 属性名与属性值之间以----分割
    return "name----{0}****".format($('#query_name').val())
}
$(document).ready(function () {
    //点击新增按钮的事件
    $('#add-obj').click(function () {
        console.log("you clicked add-obj!");
        let title = "新增";
        let add_content = '\
            <div class="pl-3 pr-3">\
                照片\
                <div class="divupload">\
                    <img src="" alt="">\
                    <input class="inputupload" type="file" id="uploadfile">\
                </div>\
                <p>标签<textarea rows="1" cols="40" id="tag"></textarea></p>\
                <p>描述<textarea rows="3" cols="40" id="comment"></textarea></p>\
                <p><span class="errmsg" id="errmsg"></p>\
            </div>\
            ';
        let get_add_data = function () {
            let data = new FormData();
            data.append('post_type', 'add');
            data.append('uploadfile', $('#uploadfile')[0].files[0]);
            data.append('tag', $('#tag').val());
            data.append('comment', $('#comment').val());
            return data;
        };
        modify_obj(title,add_content,get_add_data);
    });
    //点击编辑的事件
    $('button.edit-obj').click(function () {
        console.log("you clicked edit-obj button!");
        let obj_id = $(this).parent('td').parent('tr').children('td').children('label').children('input.checkbox').val();
        console.log("objid is",obj_id);
        let obj = get_obj(obj_id);
        let title = "编辑";
        let edit_content = '\
            <div class="pl-3 pr-3">\
                照片\
                <div class="divupload">\
                    <img src="{{ MEDIA_URL }}{0}" alt="">\
                    <input class="inputupload" type="file" id="uploadfile">\
                </div>\
                <p>标签<textarea rows="1" cols="40" id="tag">{1}</textarea></p>\
                <p>描述<textarea rows="3" cols="40" id="comment">{2}</textarea></p>\
                <p><span class="errmsg" id="errmsg"></p>\
            </div>\
            '.format(obj.photo, obj.tag, obj.comment);
        let get_edit_data = function () {
            let data = new FormData();
            data.append('post_type', 'edit');
            data.append('id', obj_id);
            data.append('uploadfile', $('#uploadfile')[0].files[0]);
            data.append('tag', $('#tag').val());
            data.append('comment', $('#comment').val());
            return data;
        };
        modify_obj(title, edit_content, get_edit_data);
    });
    //显示上传的图片
    $("body").on("change", "div.divupload input.inputupload", function () {
        let reads = new FileReader();
        let file = $(this).get(0).files[0];
        reads.readAsDataURL(file);
        let that = this;
        reads.onload = function (e) {
            $(that).parent().find("img").attr("src",this.result)
        };
    });
});
</script>
{% endblock script %}

{% block style %}
<style>
div.divupload {
    position:relative;
    width:240px;
    height:160px;
    border:1px dashed #ccc;
}
div.divupload img {
    position:absolute;
    max-width: 100%;
    max-height: 100%;
    left:0;
    right:0;
    top:0;
    bottom:0;
    margin:auto;
}
input.inputupload {
    display: inline-block;
    width: 100%;
    height: 100%;
    opacity: 0;
    z-index: 999;
}
table td img {
    max-height: 100px;
}
</style>
{% endblock %}

appipark1/templates/appipark1/equipment.html
{% extends 'appipark1/base_monitor.html' %}

{% block pgbody2 %}
<div class="container-fluid  col-12 col-md-10 float-md-right">
    {# 查询 #}
    <div class="row p-3 ">
        <label>查询条件(支持模糊查询)：</label>
        <label>
            <input type="text" placeholder="标签名称" class="mr-5" id="query_name" value="{{ name }}" >
        </label>
        <button type="button" class="btn btn-primary query_button">查询</button>
    </div>
    {# 新增/批量删除等按钮 #}
    <div class="row p-3">
        <button type="button" class="btn btn-primary mr-3" id="add-obj">新增</button>
        <button type="button" class="btn btn-light mr-auto" id="delete-some">批量删除</button>
        {% if deleted_visible %}
        <button type="button" class="btn btn-light mr-3 change-deleted_visible" value='False'>不显示已删除</button>
        {% else %}
        <button type="button" class="btn btn-light mr-3 change-deleted_visible" value='True'>显示已删除</button>
        {% endif %}
    </div>
    {# 表格形式展示内容 #}
    <div class="row p-3">
        <table class="table table-striped">
            {# 表头 #}
            <tr>
                <td>
                    <label for="select_all"></label>
                    <input type="checkbox" value="all" id="select_all" >
                    全选
                </td>
                <td>序号</td>
                <td>设备名称</td>
                <td>设备类型</td>
                <td>标签位置</td>
                <td>设备状态</td>
                <td>操作</td>
            </tr>
            {# 表格内容 #}
            {% for obj in obj_list %}
            <tr>
                <td>
                    <label>
                        <input class="checkbox" type="checkbox" name="table_checkbox" value="{{ obj.id }}">
                    </label>
                </td>
                <td>{{ forloop.counter }}</td>
                <td>{{ obj.name }}</td>
                <td>{{ obj.type }}</td>
                <td>{{ obj.location }}</td>
                <td>{{ obj.state }}</td>
                {% if obj.isdelete %}
                <td>
                    <button type="button" class="btn btn-link edit-obj">编辑</button>
                    <button type="button" class="btn btn-link recover-obj">恢复</button>
                </td>
                {% else %}
                <td>
                    <button type="button" class="btn btn-link edit-obj">编辑</button>
                    <button type="button" class="btn btn-link delete-obj">删除</button>
                </td>
                {% endif %}
            </tr>
            {% endfor %}
        </table>
    </div>
    {# 分页 #}
    <div class="row pl-3">
        <div id="pager" class="float-right">
            <nav aria-label="Page navigation">
                <ul class="pagination" per_page={{ pager.per_page|safe }}>
                    {# 页面信息 #}
                    {{ pager.pager|safe }}
                </ul>
            </nav>
        </div>
    </div>
</div>
{% endblock pgbody2 %}

{% block script %}
<script>
//定义query时传送给服务器的消息
function get_query_str() {
    //从当前网页获取query_info
    //每条属性之间以****分割符间隔开， 属性名与属性值之间以----分割
    return "name----{0}****".format($('#query_name').val())
}
$(document).ready(function () {
    //点击新增按钮的事件
    $('#add-obj').click(function () {
        console.log("you clicked add-obj!");
        let title = "新增";
        let add_content = '<div>\
            <p class="pl-3 pr-3">设备名称<textarea rows="1" cols="40" id="name"></textarea></p>\
            <p class="pl-3 pr-3">设备类型<textarea rows="1" cols="40" id="type"></textarea></p>\
            <p class="pl-3 pr-3">设备位置<textarea rows="3" cols="40" id="location"></textarea></p>\
            <p class="pl-3 pr-3"><span class="errmsg" id="errmsg"></p>\
            </div>';
        let get_add_data = function () {
            let data = new FormData();
            data.append('post_type', 'add');
            data.append('name', $('#name').val());
            data.append('type', $('#type').val());
            data.append('location', $('#location').val());
            return data;
        };
        modify_obj(title,add_content,get_add_data);
    });
    //点击编辑的事件
    $('button.edit-obj').click(function () {
        console.log("you clicked edit-obj button!");
        let obj_id = $(this).parent('td').parent('tr').children('td').children('label').children('input.checkbox').val();
        console.log("objid is",obj_id);
        let obj = get_obj(obj_id);
        let title = "编辑";
        let edit_content = '<div>\
            <p class="pl-3 pr-3">设备名称<textarea rows="1" cols="40" id="name">{0}</textarea></p>\
            <p class="pl-3 pr-3">设备类型<textarea rows="1" cols="40" id="type">{1}</textarea></p>\
            <p class="pl-3 pr-3">设备位置<textarea rows="3" cols="40" id="location">{2}</textarea></p>\
            <p class="pl-3 pr-3"><span class="errmsg" id="errmsg"></p>\
            </div>'.format(obj.name, obj.type, obj.location);
        let get_edit_data = function () {
            let data = new FormData();
            data.append('post_type', 'edit');
            data.append('id', obj_id);
            data.append('name', $('#name').val());
            data.append('type', $('#type').val());
            data.append('location', $('#location').val());
            return data;
        };
        modify_obj(title, edit_content, get_edit_data);
    });
});
</script>
{% endblock script %}

appipark1/templates/appipark1/index.html
{% extends 'appipark1/base.html' %}

{% block pgbody1 %}
<div>
这里是app.index页面
</div>
{% endblock %}

appipark1/templates/appipark1/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link href="{% static 'bootstrap-4.5.0-dist/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'appipark1/login/login.css' %}" rel="stylesheet">
    <title>用户登录</title>
</head>
<body>
    <div class="signin">
        <div class="signin-head">
            <h1>
                <img src="{% static 'appipark1/login/fjthcc.ico' %}" alt="">
                福建天海
            </h1>
        </div>
        <form class="signin-form" method="post" action="{% url 'ipark1:login' %}">
            {% csrf_token %}
            <label>
                <input type="text" class="form-control" placeholder="用户名" required autofocus name="username" />
            </label>
            <label>
                <input type="password" class="form-control" placeholder="密码" required name="password" />
            </label>
            <button class="btn btn-lg btn-warning btn-block" type="submit">登录</button>
            <p class="text-danger">{{ msg }}</p>
        </form>
    </div>
</body>
</html>

appipark1/templates/appipark1/monitor.html
{% extends 'appipark1/base_monitor.html' %}

{% block pgbody2 %}
monitor.index
{% endblock pgbody2 %}