app/urls.py
from django.urls import path

from . import views

app_name = 'app'

urlpatterns = [
    path('', views.index, name='index'),
]

appipark2/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from . import views, forms

# 定义url命名空间
app_name = 'ipark2'

urlpatterns = [
    # index页
    # path('', login_required(views.index), name='index'),
    path('', views.index, name='index'),
    # 登录页
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', login_required(views.logout), name='logout'),
    # 班车线路
    path('routelist/', views.RoutListView.as_view(), name='route'),
    path('route/edit/<str:objname>/', views.RouteEditView.as_view()),
    path('route/<objname>/', views.RouteView.as_view()),
    # 车辆
    path('vehiclelist/', views.ObjListView.as_view(), {'form': forms.VehicleForm}, name='vehicle'),
    # 设备
    path('equipmentlist/', views.ObjListView.as_view(), {'form': forms.EquipmentForm}, name='equipment'),
    # 上报location
    path('location/report/', views.location_report),
    path('location/record/', views.LocationRecordListView.as_view(), name='location'),
]

project/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from django.views.static import serve

from project import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    # app
    path('', include('app.urls', namespace='app')),
    # npo
    path('npo/', include('appnpo.urls', namespace='npo')),
    # ipark
    path('ipark/', include('appipark.urls', namespace='ipark')),
    path('ipark1/', include('appipark1.urls', namespace='ipark1')),
    path('ipark2/', include('appipark2.urls', namespace='ipark2')),
    # 媒体文件
    re_path(r'media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
]

appipark2/models.py
from operator import methodcaller
from django.db import models


class MyModel(models.Model):
    def __str__(self):
        if hasattr(self, 'name'):
            name = self.name
        else:
            name = self.pk
        return '{}: {}'.format(self._meta.verbose_name, name)

    @classmethod
    def get_listview_fields(cls):
        if hasattr(cls, 'listview_fields') and cls.listview_fields:
            return [dict(name=field.name, verbose_name=field.verbose_name) for field in cls.listview_fields]
        else:
            return [dict(name=field.name, verbose_name=field.verbose_name) for field in cls._meta.fields if field.name != 'id']

    def values_to_listview_dict(self):
        dict_obj = {}
        if hasattr(self, 'listview_fields'):
            listview_fields = self.listview_fields
        else:
            listview_fields = [field for field in self._meta.fields if field.name != 'id']
        for field in listview_fields:
            method_name = 'get_{}_display'.format(field.name)
            if hasattr(self, method_name):
                dict_obj[field.name] = methodcaller(method_name)(self)
            elif field.get_internal_type() == 'ForeignKey':
                dict_obj[field.name] = str(getattr(self, field.name))
            else:
                dict_obj[field.name] = field.value_to_string(self)
        return dict_obj

    class Meta:
        abstract = True


class Equipment(MyModel):
    type_choices = [(1, 'GPS'), ]
    state_choices = [(0, '离线'), (1, '在线')]
    name = models.CharField(verbose_name='终端名称', max_length=40, unique=True)
    eid = models.CharField(verbose_name='终端标识', max_length=12, unique=True)
    type = models.IntegerField(verbose_name='终端类型', choices=type_choices)
    state = models.IntegerField(verbose_name='终端状态', choices=state_choices)
    comment = models.CharField(verbose_name='备注', max_length=200, blank=True)

    listview_fields = [name, eid, type, state]

    class Meta:
        verbose_name = '设备'


class Vehicle(MyModel):
    type_choices = [(1, '小巴'), (2, '中巴')]
    name = models.CharField(verbose_name='车牌号', max_length=40, unique=True)
    type = models.IntegerField(verbose_name='车辆类型', choices=type_choices)
    location = models.ForeignKey(Equipment, on_delete=models.PROTECT, verbose_name='定位设备')
    comment = models.CharField(verbose_name='备注', max_length=200, blank=True)

    listview_fields = [name, type, location]

    class Meta:
        verbose_name = '车辆'


class Route(models.Model):
    choice_routetype = [(1, '早班车'), (2, '晚班车')]
    name = models.CharField(verbose_name='线路名称', max_length=40, unique=True)
    type = models.IntegerField(verbose_name='线路类型', choices=choice_routetype)
    runningtime = models.CharField(verbose_name='运行时间', max_length=100)
    vehicle = models.ForeignKey(Vehicle, on_delete=models.PROTECT, verbose_name='车牌号')
    comment = models.CharField(verbose_name='备注', max_length=200, blank=True)

    class Meta:
        verbose_name = '班车线路'


class Polyline(models.Model):
    points = models.TextField()
    orderid = models.IntegerField()
    route = models.ForeignKey('Route', on_delete=models.PROTECT)


class Station(models.Model):
    name = models.CharField(verbose_name='站点名称', max_length=40)
    lng = models.FloatField(verbose_name='站点经度')
    lat = models.FloatField(verbose_name='站点纬度')
    route = models.ForeignKey(Route, on_delete=models.PROTECT)
    orderid = models.IntegerField(verbose_name='站点序号')

    def __str__(self):
        return self.name


class LocationRecord(MyModel):
    eid = models.CharField(verbose_name='终端标识', max_length=12)
    time = models.DateTimeField(verbose_name='定位时间', auto_now=True)
    lng = models.FloatField(verbose_name='经度')
    lat = models.FloatField(verbose_name='纬度')

    class Meta:
        verbose_name = '定位记录'


class RoutePath(models.Model):
    route = models.ForeignKey(Route, on_delete=models.PROTECT)
    pathindex = models.IntegerField()
    orderid = models.IntegerField()
    lng = models.FloatField()
    lat = models.FloatField()

appipark2/forms.py
from django.forms import ModelForm
from . import models


class EquipmentForm(ModelForm):
    class Meta:
        model = models.Equipment
        fields = '__all__'


class VehicleForm(ModelForm):
    class Meta:
        model = models.Vehicle
        fields = '__all__'


class RouteForm(ModelForm):
    class Meta:
        model = models.Route
        fields = '__all__'

class LocationRecordForm(ModelForm):
    class Meta:
        model = models.LocationRecord
        fields = '__all__'

appipark2/views.py
import json
from datetime import datetime
from django.contrib import auth
# from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from django.views import View
from django.shortcuts import render, redirect
from django.http import JsonResponse
from . import models, forms


class MyView(View):
    def post(self, request, *args, **kwargs):
        respon = {'errmsg': []}
        post_type = request.POST.get('post_type')
        post_type = post_type.split('****')
        for pos in post_type:
            handler = getattr(self, pos, self.post_type_not_allowed)
            result = handler(request, *args, **kwargs)
            if result['errmsg']:
                respon['errmsg'] += result['errmsg']
            else:
                respon.update(result)
        if respon['errmsg']:
            respon['msg'] = 'err'
        else:
            respon['msg'] = 'success'
        return JsonResponse(respon)

    def post_type_not_allowed(self, request,  *args, **kwargs):
        return {'errmsg': ['post_type error', ]}


class AppView(View):

    # @classmethod
    # def as_view(cls, **initkwargs):
    #     view = super(AppView, cls).as_view(**initkwargs)
    #     return login_required(view)

    def post(self, request, *args, **kwargs):
        respon = {'errmsg': []}
        post_type = request.POST.get('post_type')
        post_type = post_type.split('****')
        for pos in post_type:
            handler = getattr(self, pos, self.post_type_not_allowed)
            result = handler(request, *args, **kwargs)
            if result['errmsg']:
                respon['errmsg'] += result['errmsg']
            else:
                respon.update(result)
        if respon['errmsg']:
            respon['msg'] = 'err'
        else:
            respon['msg'] = 'success'
        return JsonResponse(respon)

    def post_type_not_allowed(self, request,  *args, **kwargs):
        return {'errmsg': ['post_type error', ]}


class ObjListView(AppView):

    def get(self, request, form):
        model = form._meta.model
        context = {
            'modelname': model._meta.verbose_name,
            'fields': model.get_listview_fields()
        }
        obj_list = model.objects.all()
        context['obj_list'] = [obj.values_to_listview_dict() for obj in obj_list]
        return render(request, 'appipark2/objlist.html', context=context)

    def get_model_form_info(self, request, form):
        result = {'errmsg': []}
        model = form._meta.model
        objname = request.POST.get('objname')
        if not objname:
            result['form'] = form().as_ul()
        else:
            obj = model.objects.filter(name=objname)[0]
            result['form'] = form(instance=obj).as_ul()
        return result

    def add_obj(self, request, form):
        result = {'errmsg': []}
        obj_form = form(request.POST)
        if obj_form.errors:
            result['errmsg'].append(obj_form.errors)
        else:
            obj_form.save()
        return result

    def delete_obj(self, request, form):
        result = {'errmsg': []}
        objname = request.POST.get('objname')
        model = form._meta.model
        model.objects.filter(name=objname).delete()
        return result

    def edit_obj(self, request, form):
        result = {'errmsg': []}
        objname = request.POST.get('objname')
        model = form._meta.model
        obj = model.objects.filter(name=objname)[0]
        obj_form = form(request.POST, instance=obj)
        if obj_form.errors:
            result['errmsg'].append(obj_form.errors)
        else:
            obj_form.save()
        return result


class RoutListView(AppView):

    def get(self, request):
        context = {}
        obj_list = models.Route.objects.all()
        station_list = models.Station.objects.all().order_by('route_id', 'orderid')
        dict_objs = []
        for obj in obj_list:
            dict_obj = {
                'name': obj.name,
                'type': obj.get_type_display(),
                'runningtime': obj.runningtime,
                'vehicle': obj.vehicle.name,
            }
            stations = station_list.filter(route_id=obj.id)
            if stations:
                dict_obj['station_start'], dict_obj['station_end'] = stations[0], stations[len(stations)-1]
            else:
                dict_obj['station_start'], dict_obj['station_end'] = '', ''
            dict_objs.append(dict_obj)
        context['obj_list'] = dict_objs
        return render(request, 'appipark2/route_list.html', context=context)

    def get_route_form_info(self, request):
        result = {
            'errmsg': [],
            'form': forms.RouteForm().as_ul(),
        }
        return result

    def add_route(self, request):
        result = {'errmsg': []}
        route_form = forms.RouteForm(request.POST)
        if route_form.errors:
            result['errmsg'].append(route_form.errors)
        else:
            route_form.save()
        return result

    def delete_route(self, request):
        result = {'errmsg': []}
        objname = request.POST.get('objname')
        models.Route.objects.filter(name=objname).delete()
        return result


class RouteEditView(AppView):
    def get(self, request, objname):
        return render(request, 'appipark2/route_edit.html')

    def get_route_fields(self, request, objname):
        result = {
            'errmsg': [],
            'route_fields': []
        }
        route = models.Route.objects.filter(name=objname)[0]
        for field in route._meta.fields:
            if field.name != 'id':
                result_fieid = {
                    'name': field.name,
                    'verbose_name': field.verbose_name,
                    'value': field.value_to_string(route)
                }
                if field.choices:
                    result_fieid['choices'] = field.choices
                result['route_fields'].append(result_fieid)
        return result

    def get_route_form_info(self, request, objname):
        result = {'errmsg': []}
        obj = models.Route.objects.filter(name=objname)[0]
        result['form'] = forms.RouteForm(instance=obj).as_ul()
        return result

    def get_stations(self, request, objname):
        result = {'errmsg': [], 'stations': []}
        route = models.Route.objects.filter(name=objname)[0]
        stations = models.Station.objects.filter(route_id=route.id).order_by('orderid')
        for station in stations:
            result['stations'].append({
                'name': station.name,
                'lng': station.lng,
                'lat': station.lat,
            })
        return result

    def get_route_polylines(self, request, objname):
        result = {'errmsg': [], 'polylines': []}
        route = models.Route.objects.filter(name=objname)[0]
        polylines = models.Polyline.objects.filter(route_id=route.id).order_by('orderid')
        for polyline in polylines:
            result['polylines'].append(polyline.points)
        return result

    def get_routepath(self, request, objname):
        result = {'errmsg': [], 'routepath': []}
        route = models.Route.objects.filter(name=objname)[0]
        path = models.RoutePath.objects.filter(route_id=route.id).order_by('orderid')
        for point in path:
            result['routepath'].append({
                'lng': point.lng,
                'lat': point.lat,
                'pathindex': point.pathindex,
            })
        return result

    def edit_route(self, request, objname):
        result = {'errmsg': []}
        print(request.POST)
        route = models.Route.objects.filter(name=objname)[0]
        route_form = forms.RouteForm(request.POST, instance=route)
        if route_form.errors:
            result['errmsg'].append(route_form.errors)
        else:
            models.Station.objects.filter(route_id=route.id).delete()
            models.RoutePath.objects.filter(route_id=route.id).delete()
            stations = json.loads(request.POST.get('stations'))
            for station in stations:
                models.Station(route=route, **station).save()
            routepath = json.loads(request.POST.get('routepath'))
            for point in routepath:
                models.RoutePath(
                    route=route,
                    orderid=point['orderid'],
                    lng=point['lng'],
                    lat=point['lat'],
                    pathindex=point['pathindex']
                ).save()
            route_form.save()
        return result


class RouteView(AppView):
    def get(self, request, objname):
        return render(request, 'appipark2/route_view.html')

    def get_route_fields(self, request, objname):
        result = {
            'errmsg': [],
            'route_fields': []
        }
        route = models.Route.objects.filter(name=objname)[0]
        result['route_fields'].append({
            'verbose_name': '线路名称',
            'value': route.name,
        })
        result['route_fields'].append({
            'verbose_name': '线路类型',
            'value': models.Route.choice_routetype[route.type],
        })
        result['route_fields'].append({
            'verbose_name': '运行时间',
            'value': route.runningtime,
        })
        result['route_fields'].append({
            'verbose_name': '车牌号',
            'value': route.vehicle.name,
        })
        return result

    def get_route_form_info(self, request, objname):
        result = {'errmsg': []}
        obj = models.Route.objects.filter(name=objname)[0]
        result['form'] = forms.RouteForm(instance=obj).as_ul()
        return result

    def get_route_stations(self, request, objname):
        result = {'errmsg': [], 'stations': []}
        route = models.Route.objects.filter(name=objname)[0]
        stations = models.Station.objects.filter(route_id=route.id).order_by('orderid')
        for station in stations:

appipark2/templates/appipark2/base.html
{% load static %}
<!DOCTYPE html>
<html lang="zh">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="initial-scale=1.0, user-scalable=no" />
        <link REL="SHORTCUT ICON" HREF="{% static 'image/fjthcc/fjthcc.ico' %}" />
        {% block page_head%}
        {% endblock %}
        <script src="{% static 'jquery/jquery-3.5.1.min.js' %}"></script>
        <script src="{% static 'appipark2/base/base.js' %}"></script>
        <script src="{% static 'popper/popper.js' %}"></script>
        <link rel="stylesheet" href="{% static 'bootstrap-4.5.0-dist/css/bootstrap.css' %}">
        <script src="{% static 'bootstrap-4.5.0-dist/js/bootstrap.js' %}"></script>
        <script src="{% static 'layer/layer.js' %}"></script>
        {% block page_style%}
        {% endblock %}
        {% if title%}
        <title>{{ title }}</title>
        {% endif %}
    </head>
    <body>
        {% block page_body %}
        {% endblock %}
        <div>{% csrf_token %}</div>
        {% block page_script%}
        {% endblock %}
    </body>
</html>

appipark2/templates/appipark2/base_route_manage.html
{% extends "appipark2/base.html" %}
{% load static %}

{% block page_body%}
    <div class="container-fluid col-11">
        <nav name="page_top" class="row navbar navbar-light" style="background-color: #e3f2fd;">
            <a class="navbar-brand" href="{% url 'ipark2:index' %}"><img src="{% static 'img/fjthcc.ico' %}" width="30" height="30" class="d-inline-block align-top" alt="">福建天海通信ipark</a>
            <ul class="nav nav-tabs mr-auto" name="page_top_menus">
                <li class="nav-item" name="page_top_menu"><a class="nav-link" href="{% url 'ipark2:route' %}">线路列表</a></li>
                <li class="nav-item" name="page_top_menu"><a class="nav-link" href="{% url 'ipark2:vehicle' %}">车辆列表</a></li>
                <li class="nav-item" name="page_top_menu"><a class="nav-link" href="{% url 'ipark2:equipment' %}">设备列表</a></li>
                <li class="nav-item" name="page_top_menu"><a class="nav-link" href="{% url 'ipark2:location' %}">定位记录</a></li>
            </ul>
            <ul class="nav">
                <li class="nav-item"><a class="nav-link">欢迎, {{ request.user.username }}</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'ipark2:logout' %}">注销<span class="sr-only">(current)</span></a></li>
            </ul>
        </nav>
        <div name="page_body" class="row">
            {% block page_body1 %}
            {% endblock %}
        </div>
    </div>
{% endblock %}

{% block page_script %}
<script type="text/javascript">
// 设置当前标签 active
for(const url of $('ul[name="page_top_menus"] li[name="page_top_menu"]')){
    let a = $(url).find('a');
    if(a.attr('href') === window.location.pathname){
        a.addClass('active');
    }
}
</script>
    {% block page_script1 %}
    {% endblock %}
{% endblock %}

appipark2/templates/appipark2/index.html
{% extends 'appipark2/base_route_manage.html' %}

{% block page_body1 %}
    appipark.index
{% endblock %}

appipark2/templates/appipark2/location_record_list.html
{% extends 'appipark2/base_route_manage.html' %}

{% block page_body1 %}
<div class="container-fluid">
    <div class="row mt-3">
        <table class="table table-striped">
            <thead class="thead-dark">
                <tr>
                    <th scope="col">序号</th>
                    {% for field in fields %}
                        <th scope="col">{{ field.verbose_name }}</th>
                    {% endfor %}
                    <th scope="col">操作</th>
                </tr>
            </thead>
            <tbody>
                {% for obj in obj_list %}
                <tr>
                    <th scope="row">{{ forloop.counter }}</th>
                    {% for field in fields %}
                        {% for key, value in obj.items %}
                            {% if key == field.name %}
                            <td>{{ value }}</td>
                            {% endif %}
                        {% endfor %}
                    {% endfor %}
                    <td>
                        <button type="button" class="btn btn-link" name="delete_obj" objname="{{obj.name}}">删除</button>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

{% block page_script1 %}
<script type="text/javascript">
//注册 delete_obj 按钮
$(document).on('click', 'button[name="delete_obj"]', function () {
    let objname = this.getAttribute("objname");
    layer.confirm('确定要删除{{ modelname }}--{0}???'.format(objname), {btn: ['确定','返回']}, function () {
        let post_data = new FormData();
        post_data.append('post_type', 'delete_obj');
        post_data.append('objname', objname);
        $.ajax({url:'', type:'post', contentType:false, processData:false, dataType:'json', data:post_data, success:function(respon){if(respon.msg !== 'success'){layer.msg(JSON.stringify(respon.errmsg));}else{
            location.href = "";
        }}});
    });
});
</script>
{% endblock %}

appipark2/templates/appipark2/login.html
{% load static %}
<!DOCTYPE html>
<html lang="zh">
<head>
    <meta charset="UTF-8">
    <link href="{% static 'bootstrap4/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'appipark/login/login.css' %}" rel="stylesheet">
    <link REL="SHORTCUT ICON" HREF="{% static 'img/fjthcc.ico' %}" />
    <title>登录</title>
</head>
<body>
    <div class="signin">
        <div class="signin-head">
            <h1><img src="{% static 'appipark/login/fjthcc.ico' %}" alt="">福建天海</h1>
        </div>
        <form class="signin-form" method="post" action="{% url 'appipark:login' %}">
            {% csrf_token %}
            <label>
                <input type="text" class="form-control" placeholder="用户名" required autofocus name="username" />
            </label>
            <label>
                <input type="password" class="form-control" placeholder="密码" required name="password" />
            </label>
            <button class="btn btn-lg btn-warning btn-block" type="submit">登录</button>
            {% if errmsg %}
            <p class="text-danger">{{ errmsg }}</p>
            {% endif %}
        </form>
    </div>
</body>
</html>

appipark2/templates/appipark2/objlist.html
{% extends 'appipark2/base_route_manage.html' %}

{% block page_body1 %}
<div class="container-fluid">
    <div class="row">
        <button type="button" class="btn btn-link" name="add_obj">新增{{ modelname }}</button>
    </div>
    <div class="row">
        <table class="table table-striped">
            <thead class="thead-dark">
                <tr>
                    <th scope="col">序号</th>
                    {% for field in fields %}
                        <th scope="col">{{ field.verbose_name }}</th>
                    {% endfor %}
                    <th scope="col">操作</th>
                </tr>
            </thead>
            <tbody>
                {% for obj in obj_list %}
                <tr>
                    <th scope="row">{{ forloop.counter }}</th>
                    {% for field in fields %}
                        {% for key, value in obj.items %}
                            {% if key == field.name %}
                            <td>{{ value }}</td>
                            {% endif %}
                        {% endfor %}
                    {% endfor %}
                    <td>
                        <button type="button" class="btn btn-link" name="edit_obj" objname={{obj.name}}>编辑</button>
                        <button type="button" class="btn btn-link" name="delete_obj" objname="{{obj.name}}">删除</button>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

{% block page_script1 %}
<script type="text/javascript">
// 注册add_obj 按钮
$(document).on('click', 'button[name="add_obj"]', function () {
    let post_data = new FormData();
    post_data.append('post_type', 'get_model_form_info');
    $.ajax({url:'', type:'post', contentType:false, processData:false, dataType:'json', data:post_data, success:function(respon){if(respon.msg !== 'success'){layer.msg(JSON.stringify(respon.errmsg));}else{
        let title = '新增{{ modelname }}';
        let content = get_form_content('add_obj', respon.form);
        layer.open({type: 1, closeBtn: 0, offset: 'r', area: ['40%', '100%'], shade: 0.5, btn:['提交','返回'], title: title, content:content, yes:function(){
            let post_data = new FormData($("form[name='add_obj']")[0]);
            post_data.append('post_type', 'add_obj');
            $.ajax({url:'', type:'post', contentType:false, processData:false, dataType:'json', data:post_data, success:function(respon){if(respon.msg !== 'success'){layer.msg(JSON.stringify(respon.errmsg));}else{
                location.href = "";
            }}});
        }});
    }}});
});

//注册 delete_obj 按钮
$(document).on('click', 'button[name="delete_obj"]', function () {
    let objname = this.getAttribute("objname");
    layer.confirm('确定要删除{{ modelname }}--{0}???'.format(objname), {btn: ['确定','返回']}, function () {
        let post_data = new FormData();
        post_data.append('post_type', 'delete_obj');
        post_data.append('objname', objname);
        $.ajax({url:'', type:'post', contentType:false, processData:false, dataType:'json', data:post_data, success:function(respon){if(respon.msg !== 'success'){layer.msg(JSON.stringify(respon.errmsg));}else{
            location.href = "";
        }}});
    });
});

//注册 edit_obj 按钮
$(document).on('click', 'button[name="edit_obj"]', function () {
    let objname = this.getAttribute("objname");
    let post_data = new FormData();
    post_data.append('post_type', 'get_model_form_info');
    post_data.append('objname', objname);
    $.ajax({url:'', type:'post', contentType:false, processData:false, dataType:'json', data:post_data, success:function(respon){if(respon.msg !== 'success'){layer.msg(JSON.stringify(respon.errmsg));}else{
        let title = '编辑{{ modelname }}';
        let content = get_form_content('edit_obj', respon.form);
        layer.open({type: 1, closeBtn: 0, offset: 'r', area: ['40%', '100%'], shade: 0.5, btn:['提交','返回'], title: title, content:content, yes:function(){
            let post_data = new FormData($("form[name='edit_obj']")[0]);
            post_data.append('post_type', 'edit_obj');
            post_data.append('objname', objname);
            $.ajax({url:'', type:'post', contentType:false, processData:false, dataType:'json', data:post_data, success:function(respon){if(respon.msg !== 'success'){layer.msg(JSON.stringify(respon.errmsg));}else{
                location.href = "";
            }}});
        }});
    }}});
});

function get_form_content(form_name, str) {
    let lis = $('<div>{0}</div>'.format(str)).find('li').addClass("list-group-item");
    let arr_lis = [];
    for(let i=0; i<lis.length; i++){
        arr_lis.push(lis[i].outerHTML);
    }
    return '<form name="{0}"><ul class="list-group">{1}</ul></form>'.format(form_name, arr_lis.join(''));
}
</script>
{% endblock %}